# -*- coding: utf-8 -*-
"""Specs Chunk 2: Domains 5 to 8 (TF-033 to TF-060) - 28 templates"""

CHUNK_2 = [
    # --- DOMAIN 5: Defense Evasion & Injection (7) ---
    ("TF-033", "Antivirus Filter Altitude Update", "defense_evasion", "evidence_analysis", "benign", "train", None, "Windows", "server", "SYSTEM",
     "Antivirus File System Minifilter Driver Registration", "informational", "Driver Altitude Registration",
     [("registry_modification", "HKLM\\System\\CurrentControlSet\\Services\\WdFilter\\Instances altitude updated to 328010", '{"key": "HKLM\\\\System\\\\CurrentControlSet\\\\Services\\\\WdFilter", "altitude": "328010"}'),
      ("process_creation", "MsMpEng.exe performed routine signature engine update", '{"parent": "services.exe", "process": "MsMpEng.exe"}')],
     [("Microsoft Defender antivirus engine registered legitimate file system minifilter driver.", ["EVT-001", "EVT-002"], "informational")],
     "Standard endpoint protection platform operational maintenance.", [],
     [("Close alert as normal antivirus driver configuration.", "low", "Expected security tool telemetry.")], None),

    ("TF-034", "CMD Obfuscated with Carets and Substrings", "defense_evasion", "alert_triage", "suspicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "employee01",
     "Heavily Obfuscated Command Shell Syntax Detected", "medium", "Command Obfuscation",
     [("process_creation", "cmd.exe executed with heavy caret insertion 'c^m^d^.^e^x^e /c p^o^w^e^r^s^h^e^l^l'", '{"command_line": "c^m^d^.^e^x^e /c p^o^w^e^r^s^h^e^l^l -c write-host test"}'),
      ("powershell_log", "PowerShell spawned from obfuscated cmd executed write-host test", '{"script": "write-host test"}')],
     [("Command interpreter executed with deliberate string obfuscation techniques designed to bypass static signature filters.", ["EVT-001", "EVT-002"], "medium")],
     "Caret obfuscation is almost exclusively used by evasion tools, although payload in this instance was benign test command.",
     [("T1027.010", "Command Obfuscation", "Defense Evasion", ["EVT-001"]),
      ("T1059.003", "Windows Command Shell", "Execution", ["EVT-001"])],
     [("Identify user or process responsible for generating obfuscated command string.", "medium", "Check for testing software.")], None),

    ("TF-035", "Process Hollowing into Svchost", "defense_evasion", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "intern01",
     "Process Hollowing Memory Injection Pattern in svchost.exe", "high", "Process Injection",
     [("process_creation", "Word document spawned word_macro.exe which created suspended svchost.exe", '{"parent": "word_macro.exe", "child": "svchost.exe", "suspended": true}'),
      ("sysmon_event", "Sysmon Event ID 8: CreateRemoteThread into suspended svchost.exe address 0x00400000", '{"event_id": 8, "target": "svchost.exe", "address": "0x00400000"}'),
      ("network_connection", "Hollowed svchost.exe initiated outbound connection to external IP {ext_ip}:443", '{"process": "svchost.exe", "dest_ip": "{ext_ip}", "port": 443}')],
     [("Suspended system process svchost.exe unmapped and injected with shellcode by untrusted parent.", ["EVT-001", "EVT-002"], "high"),
      ("Hollowed svchost process initiated external C2 communication.", ["EVT-003"], "high")],
     "Process hollowing into svchost.exe followed by network activity is an advanced evasion technique characteristic of custom malware loaders.",
     [("T1055", "Process Injection", "Defense Evasion", ["EVT-001", "EVT-002"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-003"])],
     [("Terminate process svchost.exe PID and isolate endpoint {hostname}.", "immediate", "Stop injected process execution.")], None),

    ("TF-036", "DLL Search Order Hijacking version.dll", "defense_evasion", "alert_triage", "confirmed_malicious", "train", None, "Windows", "workstation", "employee02",
     "Malicious DLL Sideloaded by Vulnerable Signed Binary", "high", "DLL Sideloading",
     [("file_modification", "Unsigned rogue version.dll dropped into application directory C:\\Program Files\\LegacyApp\\", '{"file": "version.dll", "path": "C:\\\\Program Files\\\\LegacyApp\\\\version.dll"}'),
      ("process_creation", "LegacyApp.exe loaded rogue version.dll instead of System32\\version.dll", '{"loader": "LegacyApp.exe", "loaded_dll": "C:\\\\Program Files\\\\LegacyApp\\\\version.dll"}'),
      ("network_connection", "LegacyApp.exe established HTTPS beacon to {domain} ({ext_ip})", '{"dest_ip": "{ext_ip}", "domain": "{domain}", "port": 443}')],
     [("Adversary planted rogue DLL in application directory to achieve DLL search order hijacking.", ["EVT-001", "EVT-002"], "high"),
      ("Legitimate signed application abused to proxy encrypted external C2 traffic.", ["EVT-003"], "critical")],
     "Confirmed DLL search order hijacking with active proxy C2 connection initiated from legitimate binary context.",
     [("T1036.005", "Match Legitimate Name or Location", "Defense Evasion", ["EVT-001", "EVT-002"]),
      ("T1204.002", "Malicious File", "Execution", ["EVT-002"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-003"])],
     [("Remove rogue version.dll and quarantine file immediately.", "immediate", "Neutralize hijacked DLL."),
      ("Audit endpoint {hostname} for persistence keys triggering LegacyApp.exe.", "high", "Eliminate persistence.")], None),

    ("TF-037", "Memory Injection Alert Terminated Before Capture", "defense_evasion", "alert_triage", "insufficient_evidence", "train", "likely_malicious_vs_insufficient_evidence", "Windows", "workstation", "employee05",
     "VirtualAllocEx Memory Protection Warning from Terminated Process", "medium", "Transient Injection Anomaly",
     [("sysmon_event", "Sysmon detected VirtualAllocEx call with PAGE_EXECUTE_READWRITE from PID 4812", '{"event_id": 10, "source_pid": 4812, "protection": "PAGE_EXECUTE_READWRITE"}'),
      ("process_creation", "Source process PID 4812 terminated within 15 milliseconds before metadata capture", '{"pid": 4812, "terminated": true}')],
     [("Suspicious memory allocation detected with executable permissions but source process terminated immediately.", ["EVT-001", "EVT-002"], "medium")],
     "Transient process lifecycle prevented forensic collection of executable image path, hash, or target thread context.", [],
     [("Extract crash dump and MFT records for PID 4812 to identify executable binary.", "high", "Identify terminated binary.")],
     ["NTFS Master File Table ($MFT) delta records", "Volume Shadow Copy memory snapshot"]),

    ("TF-038", "Visual Studio Debugger Process Attach", "defense_evasion", "evidence_analysis", "benign", "val", None, "Windows", "workstation", "developer01",
     "Debugger Process Attached to Local Target Process", "low", "Developer Debugging Tool",
     [("process_creation", "devenv.exe (Visual Studio) attached debugger to target test_service.exe", '{"debugger": "devenv.exe", "target": "test_service.exe"}'),
      ("authentication", "Active developer interactive session on dedicated development workstation", '{"user": "developer01", "workstation": "DEV-WS-030"}')],
     [("Legitimate integrated development environment attached debugger to locally compiled test executable.", ["EVT-001", "EVT-002"], "low")],
     "Expected software engineering development activity on designated developer system.", [],
     [("Close alert as verified local application debugging.", "low", "Standard developer workflow.")], None),

    ("TF-039", "Sysmon Remote Thread Injection Missing Call Stack", "defense_evasion", "investigation_planning", "insufficient_evidence", "test", None, "Windows", "server", "SYSTEM",
     "CreateRemoteThread Event Recorded Without Stack Telemetry", "low", "Remote Thread Logging Gap",
     [("sysmon_event", "Sysmon Event 8 recorded CreateRemoteThread from spoolsv.exe to rundll32.exe with empty CallTrace", '{"event_id": 8, "source": "spoolsv.exe", "target": "rundll32.exe", "call_trace": null}'),
      ("process_creation", "rundll32.exe spawned by spoolsv.exe with legitimate print provider argument", '{"command_line": "rundll32.exe C:\\\\Windows\\\\System32\\\\spool\\\\DRIVERS\\\\printui.dll,PrintUIEntry"}')],
     [("Thread injection recorded between print spooler and rundll32, but missing call trace prevents verifying if benign print job.", ["EVT-001", "EVT-002"], "low")],
     "Print spooler architecture commonly spawns helper threads, but without call trace data anomalous injection cannot be ruled out.", [],
     [("Enable enhanced call stack logging in Sysmon configuration on print servers.", "medium", "Prevent future telemetry blindspots.")],
     ["Sysmon Driver debug trace", "PrintService Operational log"]),

    # --- DOMAIN 6: Credential Access (7) ---
    ("TF-040", "LSASS Memory Dump via Comsvcs.dll", "credential_access", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "server", "it_admin01",
     "MiniDump Function Invoked Against LSASS via Rundll32", "high", "LSASS Memory Dumping",
     [("process_creation", "rundll32.exe comsvcs.dll MiniDump targeting lsass.exe PID", '{"command_line": "rundll32.exe C:\\\\Windows\\\\System32\\\\comsvcs.dll MiniDump 624 C:\\\\Temp\\\\lsass.dmp full"}'),
      ("file_modification", "Large memory dump file lsass.dmp created in C:\\Temp", '{"path": "C:\\\\Temp\\\\lsass.dmp", "size": 48192000}')],
     [("Adversary dumped Local Security Authority Subsystem Service (LSASS) process memory to disk using built-in Windows DLL.", ["EVT-001", "EVT-002"], "high")],
     "Abusing comsvcs.dll MiniDump to dump LSASS memory is a signature credential harvesting method.",
     [("T1003.001", "LSASS Memory", "Credential Access", ["EVT-001", "EVT-002"])],
     [("Immediately delete dump file C:\\Temp\\lsass.dmp and isolate server {hostname}.", "immediate", "Prevent credential extraction."),
      ("Reset credentials for all accounts logged into server {hostname}.", "immediate", "Mitigate exposed hashes.")], None),

    ("TF-041", "Mimikatz Sekurlsa Logonpasswords Execution", "credential_access", "alert_triage", "confirmed_malicious", "train", None, "Windows", "workstation", "contractor01",
     "Mimikatz Credential Dumping Engine Executed", "critical", "Mimikatz In-Memory Execution",
     [("process_creation", "cmd.exe spawned unsigned mimikatz.exe in C:\\Users\\Public\\", '{"command_line": "C:\\\\Users\\\\Public\\\\mimikatz.exe privilege::debug sekurlsa::logonpasswords exit"}'),
      ("threat_intel_match", "Binary hash of mimikatz.exe matches known HackTool:Win32/Mimikatz.D", '{"tool": "Mimikatz", "hash": "{mal_hash}"}'),
      ("file_modification", "Log file credentials.txt generated in C:\\Users\\Public\\ containing plaintext credentials", '{"path": "C:\\\\Users\\\\Public\\\\credentials.txt"}')],
     [("Confirmed Mimikatz hacktool executed with debug privileges to extract plaintext passwords from memory.", ["EVT-001", "EVT-002"], "critical"),
      ("Dumped credentials saved to staging file on disk.", ["EVT-003"], "critical")],
     "Definitive credential dumping confirmed by threat intelligence binary match and explicit logonpasswords command sequence.",
     [("T1003.001", "LSASS Memory", "Credential Access", ["EVT-001", "EVT-002"]),
      ("T1078", "Valid Accounts", "Defense Evasion", ["EVT-001"])],
     [("Immediately disconnect workstation {hostname} and seize for forensic acquisition.", "immediate", "Preserve memory artifact."),
      ("Force global password resets for all corporate domain accounts accessed from this endpoint.", "immediate", "Invalidate dumped hashes.")], None),

    ("TF-042", "Volume Shadow Copy NTDS Read Access", "credential_access", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Windows", "server", "admin01",
     "Active Directory Database Read via Volume Shadow Copy", "medium", "NTDS.dit Shadow Access",
     [("process_creation", "cmd.exe invoked vssadmin create shadow /for=C:", '{"command_line": "vssadmin create shadow /for=C:"}'),
      ("file_modification", "Copy command executed targeting \\\\?\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy1\\Windows\\NTDS\\ntds.dit", '{"target": "ntds.dit"}')],
     [("Volume shadow copy created and utilized to access locked Active Directory database file.", ["EVT-001", "EVT-002"], "medium")],
     "Shadow copy access to ntds.dit is used by legitimate backup operators but also by adversaries stealing AD hashes.",
     [("T1003.003", "NTDS", "Credential Access", ["EVT-001", "EVT-002"])],
     [("Verify whether admin01 was conducting authorized off-schedule Active Directory backup.", "medium", "Confirm authorization.")], None),

    ("TF-043", "Active Directory System State Scheduled Backup", "credential_access", "evidence_analysis", "benign", "train", None, "Windows", "server", "svc_backup",
     "Windows Server Backup Executing Scheduled System State", "informational", "System State Backup",
     [("scheduled_task", "Scheduled backup task 'NightlyDomainBackup' executed by svc_backup", '{"task": "NightlyDomainBackup", "user": "svc_backup"}'),
      ("process_creation", "wbadmin.exe start systemstatebackup -backupTarget:E: -quiet", '{"command_line": "wbadmin.exe start systemstatebackup -backupTarget:E: -quiet"}'),
      ("file_modification", "Backup catalog and encrypted VHDX written to designated backup volume E:\\", '{"volume": "E:\\\\", "success": true}')],
     [("Enterprise backup service account performed scheduled system state backup using native wbadmin utility.", ["EVT-001", "EVT-002"], "informational")],
     "Expected operational maintenance executed by dedicated backup account targeting dedicated backup volume.", [],
     [("Close alert as verified scheduled Active Directory system state backup.", "low", "Routine backup telemetry.")], None),

    ("TF-044", "Procdump Utility Missing Target Process Arguments", "credential_access", "alert_triage", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "server", "sysadmin01",
     "Procdump Execution with Unresolved Command Switches", "medium", "Process Dump Incomplete Log",
     [("process_creation", "procdump.exe spawned from command shell with command line recorded as null", '{"process": "procdump.exe", "arguments": null}'),
      ("authentication", "Interactive administrative logon active on server for sysadmin01", '{"user": "sysadmin01"}')],
     [("Dual-use diagnostic tool procdump launched by admin, but target process PID missing from log stream.", ["EVT-001", "EVT-002"], "medium")],
     "Procdump is commonly used by sysadmins to troubleshoot crashes, but also by threat actors to dump LSASS. Missing arguments prevent determination.", [],
     [("Query endpoint security agent for command line switches or check C:\\Windows\\Temp for dump files.", "high", "Identify dumped process.")],
     ["Sysmon Event ID 1 full process log", "Local file system directory listing for *.dmp"]),

    ("TF-045", "DCSync Directory Replication Abuse", "credential_access", "alert_triage", "confirmed_malicious", "val", None, "Windows", "server", "contractor01",
     "Non-DC Workstation Requesting Directory Replication (DCSync)", "critical", "DCSync Attack",
     [("authentication", "Workstation 10.0.1.77 initiated DRSUAPI RPC bind to Domain Controller with DS-Replication-Get-Changes privilege", '{"source_ip": "10.0.1.77", "rpc_interface": "DRSUAPI"}'),
      ("network_connection", "High-volume RPC traffic exchange retrieving domain password hashes for KRBTGT account", '{"target_account": "krbtgt", "bytes_transferred": 1849102}'),
      ("threat_intel_match", "Network packet payload matches known DCSync query pattern (DsGetNCChanges)", '{"protocol": "DRSUAPI", "signature": "DCSync-Mimikatz"}')],
     [("Non-domain controller workstation requested full domain replication changes via Directory Replication Service.", ["EVT-001", "EVT-002"], "critical"),
      ("Replication request specifically extracted password hash for critical krbtgt account.", ["EVT-002", "EVT-003"], "critical")],
     "Unambiguous DCSync attack: non-DC system abusing directory replication to retrieve domain password hashes without touching DC disk.",
     [("T1003.003", "NTDS", "Credential Access", ["EVT-001", "EVT-002"]),
      ("T1078.002", "Domain Accounts", "Defense Evasion", ["EVT-001"])],
     [("Immediately sever network connectivity for pivot host 10.0.1.77.", "immediate", "Stop replication theft."),
      ("Reset KRBTGT account password twice across the Active Directory forest.", "immediate", "Invalidate all Kerberos tickets.")], None),

    ("TF-046", "DPAPI Master Key Access Corrupted Audit", "credential_access", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "workstation", "employee01",
     "Cryptographic Vault Access Event with Corrupted Security Descriptor", "low", "DPAPI Access Anomaly",
     [("process_creation", "lsass.exe handled DPAPI Master Key unprotect request with truncated client PID", '{"target": "DPAPI MasterKey", "client_pid": null}'),
      ("authentication", "Local user employee01 unlocked desktop session 2 minutes prior", '{"user": "employee01"}')],
     [("Local cryptographic key access request logged by LSASS, but calling process identifier corrupted in event stream.", ["EVT-001", "EVT-002"], "low")],
     "DPAPI accesses occur routinely during browser and Outlook SSO, but corrupted PID leaves unverified possibility of rogue key extraction.", [],
     [("Collect Security Event ID 4692 and check recent credential manager queries.", "medium", "Correlate DPAPI client.")],
     ["Windows Security Event Log 4692", "Microsoft-Windows-Crypto-DPAPI operational log"]),

    # --- DOMAIN 7: Discovery & Reconnaissance (7) ---
    ("TF-047", "IT Admin Network Troubleshooting Ping Sweep", "discovery_recon", "alert_triage", "benign", "train", None, "Windows", "workstation", "it_admin01",
     "ICMP Ping Sweep Across Local Subnet", "low", "Subnet Ping Sweep",
     [("process_creation", "cmd.exe executed for /L %i in (1,1,254) do @ping -n 1 -w 100 10.0.1.%i", '{"command_line": "for /L %i in (1,1,254) do @ping -n 1 10.0.1.%i"}'),
      ("network_connection", "Sequential ICMP echo requests sent across local corporate management subnet", '{"protocol": "ICMP", "subnet": "10.0.1.0/24"}')],
     [("IT administrator executed basic command-line ping sweep during documented network subnet migration.", ["EVT-001", "EVT-002"], "low")],
     "Simple connectivity verification executed by authorized administrator from designated IT management system.", [],
     [("Close alert as authorized network connectivity troubleshooting.", "low", "Documented operational task.")], None),

    ("TF-048", "Port Scan of DC from Linux Workstation", "discovery_recon", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Linux", "workstation", "devops",
     "TCP SYN Sweep Targeting Core Ports from Linux Workstation", "medium", "Internal Port Scan",
     [("network_connection", "Workstation 10.0.1.77 sent TCP SYN packets to ports 88, 135, 139, 389, 445, 3389 on DC", '{"target": "10.0.1.15", "ports": [88, 135, 139, 389, 445, 3389]}'),
      ("firewall_log", "Internal firewall logged 45 connection attempts within 10 seconds from devops host", '{"source_ip": "10.0.1.77", "count": 45}')],
     [("Linux workstation performed sequential TCP port scan against core Domain Controller infrastructure.", ["EVT-001", "EVT-002"], "medium")],
     "Port scanning from standard development endpoints is anomalous and frequently indicates attacker reconnaissance or unauthorized network scanning tools.",
     [("T1046", "Network Service Discovery", "Discovery", ["EVT-001", "EVT-002"])],
     [("Interview user devops and inspect workstation 10.0.1.77 for installed port scanners.", "medium", "Determine scan origin.")], None),

    ("TF-049", "Automated Discovery Commands Sequence", "discovery_recon", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "contractor01",
     "Rapid Execution of System and Domain Discovery Commands", "high", "Automated Discovery Sequence",
     [("process_creation", "cmd.exe executed whoami /all, net user, net group domain_admins /domain in 15 seconds", '{"commands": ["whoami /all", "net user", "net group domain_admins /domain"]}'),
      ("process_creation", "cmd.exe executed systeminfo and nltest /dclist:CORP", '{"commands": ["systeminfo", "nltest /dclist:CORP"]}')],
     [("Automated batch sequence of system and domain enumeration commands executed in rapid succession.", ["EVT-001", "EVT-002"], "high")],
     "Rapid sequential execution of discovery utilities matches standard post-exploitation automated triage scripts.",
     [("T1087.002", "Domain Account Discovery", "Discovery", ["EVT-001"]),
      ("T1082", "System Information Discovery", "Discovery", ["EVT-002"]),
      ("T1018", "Remote System Discovery", "Discovery", ["EVT-002"])],
     [("Isolate workstation {hostname} and identify parent process that spawned discovery commands.", "high", "Halt attacker orientation.")], None),

    ("TF-050", "SYN Flood from Unmanaged Switch Missing Host Data", "discovery_recon", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Linux", "server", "root",
     "Inbound SYN Packet Spike from Unregistered IP Address", "low", "Unmanaged Network Traffic",
     [("firewall_log", "Core firewall dropped 300 half-open SYN packets from IP 192.168.2.50 targeting port 445", '{"source_ip": "192.168.2.50", "dest_port": 445, "dropped": 300}'),
      ("vulnerability_scan", "IP 192.168.2.50 absent from corporate asset inventory database and DHCP leases", '{"ip": "192.168.2.50", "registered": false}')],
     [("Network port sweep detected from internal IP address that lacks registration in asset inventory or DHCP logs.", ["EVT-001", "EVT-002"], "low")],
     "Network telemetry confirms probe activity, but unmanaged device status leaves host operating system and process ownership unknown.", [],
     [("Trace MAC address on core switch to identify physical switchport and VLAN location.", "medium", "Locate rogue hardware.")],
     ["Switch MAC address table", "802.1X network access control logs"]),

    ("TF-051", "Linux Auditd Hardware and Service Inventory", "discovery_recon", "evidence_analysis", "benign", "train", None, "Linux", "server", "secops",
     "Hardware and Service Profiling by Monitoring Agent", "informational", "Linux System Inventory",
     [("process_creation", "inventory_agent executed uname -a, lshw, and curl -s http://localhost:9100/metrics for service metrics", '{"parent": "cron", "commands": ["uname -a", "lshw", "curl -s http://localhost:9100/metrics"]}'),
      ("authentication", "Authorized SSH key logon for secops from internal jumpbox 10.0.1.15", '{"user": "secops", "service": "sshd", "source_ip": "10.0.1.15"}'),
      ("file_modification", "JSON inventory output updated in /var/log/inventory.json", '{"file": "/var/log/inventory.json"}')],
     [("Authorized monitoring agent collected standard hardware and daemon metrics via local curl probe.", ["EVT-001", "EVT-003"], "informational"),
      ("Sysadmin authenticated via authorized SSH public key from corporate jumpbox.", ["EVT-002"], "informational")],
     "Documented corporate IT infrastructure profiling job and administrative SSH check running on designated schedule.", [],
     [("Close alert as benign routine Linux inventory audit.", "low", "Verified monitoring activity.")], None),

    ("TF-052", "Linux Sudoers Enumeration by Web User", "discovery_recon", "alert_triage", "suspicious", "val", None, "Linux", "server", "www-data",
     "Web Server Account Attempting Sudo Enumeration", "medium", "Sudo Privilege Discovery",
     [("process_creation", "www-data executed 'sudo -l' and attempted to read /etc/sudoers", '{"user": "www-data", "cmd": "sudo -l"}'),
      ("authentication", "Auditd logged PAM authentication failure for www-data invoking sudo", '{"user": "www-data", "status": "FAILED"}')],
     [("Unprivileged web server service account attempted to enumerate administrative sudo permissions.", ["EVT-001", "EVT-002"], "medium")],
     "Service accounts running web servers should not invoke sudo; strongly suggests web application probe or post-exploitation check.",
     [("T1082", "System Information Discovery", "Discovery", ["EVT-001", "EVT-002"])],
     [("Review web server access logs for /var/www around execution timestamp to identify web shell or RCE.", "high", "Investigate web exploit.")], None),

    ("TF-053", "AdFind Querying Active Directory Objects", "discovery_recon", "alert_triage", "likely_malicious", "test", None, "Windows", "workstation", "intern01",
     "AdFind Utility Querying Full Domain Computer and Subnet Objects", "medium", "AdFind Discovery",
     [("process_creation", "adfind.exe executed with switches -f (objectcategory=computer) -csv", '{"command_line": "adfind.exe -f (objectcategory=computer) -csv -nodn"}'),
      ("file_modification", "CSV export file computers.csv written to C:\\Users\\intern01\\Desktop", '{"file": "computers.csv"}')],
     [("Specialized Active Directory enumeration tool AdFind used to dump full list of domain computer objects to disk.", ["EVT-001", "EVT-002"], "medium")],
     "AdFind is heavily favored by ransomware affiliates to map enterprise networks prior to lateral movement.",
     [("T1087.002", "Domain Account Discovery", "Discovery", ["EVT-001"]),
      ("T1018", "Remote System Discovery", "Discovery", ["EVT-001", "EVT-002"])],
     [("Quarantine adfind.exe and interview user regarding origin of the executable.", "high", "Mitigate network mapping.")], None),

    # --- DOMAIN 8: Lateral Movement (7) ---
    ("TF-054", "PsExec SCCM Deployment Across Workstations", "lateral_movement", "alert_triage", "benign", "train", None, "Windows", "server", "it_admin01",
     "PsExec Execution by IT Admin for Patch Deployment", "low", "Administrative Remote Execution",
     [("process_creation", "psexec.exe deployed client patch installer across workstations from management host", '{"command_line": "psexec.exe \\\\PC-042 -u CORP\\\\it_admin01 -s C:\\\\Installs\\\\patch.exe"}'),
      ("authentication", "Successful Kerberos network authentication from IT management workstation 10.0.1.15", '{"user": "it_admin01", "source_ip": "10.0.1.15"}')],
     [("Authorized IT administrator utilized PsExec with explicit admin credentials for scheduled maintenance rollout.", ["EVT-001", "EVT-002"], "low")],
     "Verified administrative software deployment activity conforming to IT operational procedures.", [],
     [("Close alert as authorized PsExec deployment.", "low", "Documented maintenance workflow.")], None),

    ("TF-055", "RDP Off-Hours Multi-Workstations", "lateral_movement", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Windows", "workstation", "employee01",
     "Sequential RDP Sessions to Multiple Internal Hosts Off-Hours", "medium", "RDP Anomaly",
     [("authentication", "Employee account employee01 initiated 4 distinct RDP sessions between 11 PM and 1 AM", '{"user": "employee01", "sessions": 4, "dest_ips": ["10.0.1.42", "10.0.1.77", "10.0.2.10", "10.0.2.25"]}'),
      ("network_connection", "Outbound TCP connections established to port 3389 across multiple subnets", '{"port": 3389, "count": 4}')],
     [("Standard user account established multiple remote desktop sessions across distinct departmental subnets during off-hours.", ["EVT-001", "EVT-002"], "medium")],
     "Sequential RDP pivoting across multiple internal systems off-hours is uncharacteristic of standard user role.",
     [("T1021.001", "Remote Desktop Protocol", "Lateral Movement", ["EVT-001", "EVT-002"])],
     [("Contact user employee01 to verify whether off-hours remote maintenance was authorized.", "medium", "Clarify user intent.")], None),

    ("TF-056", "PsExec Lateral Movement to File Server", "lateral_movement", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "server", "employee05",
     "PsExec Service Installed on File Server from Compromised Workstation", "high", "PsExec Lateral Pivot",
     [("service_creation", "PSEXESVC service created on SRV-FILE-01 from source workstation 10.0.1.77", '{"service": "PSEXESVC", "source_ip": "10.0.1.77"}'),
      ("process_creation", "PSEXESVC.exe spawned cmd.exe with SYSTEM privileges executing network discovery", '{"parent": "PSEXESVC.exe", "command": "cmd.exe /c net view"}')],
     [("Compromised business workstation initiated lateral movement to critical file server via remote service creation.", ["EVT-001", "EVT-002"], "high")],
     "Use of PsExec from an accounting workstation to pivot to file server matches adversary lateral movement playbook.",
     [("T1569.002", "Service Execution", "Execution", ["EVT-001", "EVT-002"]),
      ("T1021.002", "SMB/Windows Admin Shares", "Lateral Movement", ["EVT-001"])],
     [("Terminate PSEXESVC service on SRV-FILE-01 and isolate originating host 10.0.1.77.", "immediate", "Block lateral progression.")], None),

    ("TF-057", "WMI Remote Execution on Domain Controller", "lateral_movement", "alert_triage", "confirmed_malicious", "train", None, "Windows", "server", "admin02",
     "WMI Process Spawning on DC from Staging Host", "critical", "WMI Lateral Movement",
     [("wmi_activity", "WMI event subscription and remote process execution request received from pivot host 10.0.3.5", '{"source_ip": "10.0.3.5", "target": "Win32_Process.Create"}'),
      ("process_creation", "WmiPrvSE.exe spawned powershell.exe executing beacon dropper script", '{"parent": "WmiPrvSE.exe", "command_line": "powershell.exe -enc {enc}"}'),
      ("network_connection", "powershell.exe connected to external adversary listener {ext_ip}:8443", '{"dest_ip": "{ext_ip}", "port": 8443}')],
     [("Remote WMI execution abused to spawn child process on Domain Controller.", ["EVT-001", "EVT-002"], "high"),
      ("Spawned process established direct command-and-control connection to external IP {ext_ip}.", ["EVT-003"], "critical")],
     "Confirmed lateral movement into tier-0 infrastructure using WMI resulting in active C2 beaconing.",
     [("T1021.002", "SMB/Windows Admin Shares", "Lateral Movement", ["EVT-001"]),
      ("T1059.001", "PowerShell", "Execution", ["EVT-002"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-003"])],
     [("Immediately isolate pivot host 10.0.3.5 and terminate WMI child process tree on DC.", "immediate", "Sever adversary presence on DC.")], None),

    ("TF-058", "SMB C$ Share Connection with Null Session Telemetry", "lateral_movement", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "server", "SYSTEM",
     "Inbound Administrative Share Connection Without Client Information", "medium", "SMB Share Access Anomaly",
     [("authentication", "Event ID 5140 recorded access to administrative share \\\\*\\C$ by anonymous/null credentials", '{"event_id": 5140, "share": "C$", "user": "ANONYMOUS LOGON"}'),
      ("network_connection", "SMB session initiated over TCP port 445 but source IP dropped from packet trace", '{"port": 445, "source_ip": null}')],
     [("Administrative share accessed anonymously but network packet trace failed to retain client source IP.", ["EVT-001", "EVT-002"], "medium")],
     "Administrative share access with null credentials is high risk, but missing source IP prevents attribution or containment.", [],
     [("Check Windows Security Event 5145 and active SMB open sessions via Get-SmbSession.", "high", "Locate active connection source.")],
     ["SMB Server Operational Log", "Live Get-SmbSession output"]),

    ("TF-059", "Linux SSH Key Extraction and Lateral Movement", "lateral_movement", "alert_triage", "confirmed_malicious", "train", None, "Linux", "server", "deployer",
     "Compromised SSH Key Used to Pivot to Database Server", "high", "SSH Lateral Movement",
     [("file_modification", "Private key /home/deployer/.ssh/id_rsa accessed by unexpected web process", '{"key_path": "/home/deployer/.ssh/id_rsa", "accessor": "python3"}'),
      ("authentication", "Successful SSH login to DB-POSTGRES-01 using deployer key from DMZ web host 10.0.1.77", '{"dest_host": "DB-POSTGRES-01", "user": "deployer", "auth_method": "publickey"}'),
      ("process_creation", "Interactive bash session spawned on database host immediately dumping tables", '{"cmd": "pg_dumpall > /tmp/db_full.sql"}')],
     [("Stolen private SSH key utilized to pivot laterally from DMZ web server to production database server.", ["EVT-001", "EVT-002"], "high"),
      ("Database dump command executed immediately upon session establishment.", ["EVT-003"], "critical")],
     "Confirmed multi-host lateral pivot utilizing harvested SSH credentials to access backend database tier.",
     [("T1021.001", "Remote Desktop Protocol", "Lateral Movement", ["EVT-002"]),
      ("T1078", "Valid Accounts", "Defense Evasion", ["EVT-002"]),
      ("T1059.006", "Python", "Execution", ["EVT-001"])],
     [("Revoke SSH public key across all servers in authorized_keys files immediately.", "immediate", "Invalidate stolen key."),
      ("Isolate both DMZ pivot server and DB-POSTGRES-01.", "immediate", "Contain database access.")], None),

    ("TF-060", "Unauthenticated SMB Relay Attempt", "lateral_movement", "alert_triage", "suspicious", "train", None, "Windows", "server", "SYSTEM",
     "NTLM Relay Signature Pattern Detected Across Subnets", "medium", "SMB Relay Attempt",
     [("authentication", "Domain Controller received rapid NTLM authentication relay attempts from external IP {ext_ip}", '{"source_ip": "{ext_ip}", "protocol": "NTLMv2"}'),
      ("firewall_log", "Perimeter firewall blocked forwarded SMB negotiation packet targeting internal file share", '{"dest_port": 445, "action": "DROP"}')],
     [("External host attempted unauthenticated NTLM relay against internal domain infrastructure.", ["EVT-001", "EVT-002"], "medium")],
     "SMB relay attempts intercepted at edge firewall; potential active adversary targeting corporate NTLM weaknesses.",
     [("T1021.002", "SMB/Windows Admin Shares", "Lateral Movement", ["EVT-001", "EVT-002"])],
     [("Enforce SMB Signing and Extended Protection for Authentication across all domain servers.", "high", "Halt relay vulnerability.")], None)
]

print(f"Chunk 2 loaded: {len(CHUNK_2)} templates.")
